import {
  ActivitiesFilled,
  AlertCircleFilled,
  AlertDangerWarningFilled,
  AlertInfoFilled,
  AppleFilled,
  AppointmentFilled,
  ArrowLongDownFilled,
  ArrowLongLeftFilled,
  ArrowLongRightFilled,
  ArrowLongUpFilled,
  ArrowShortDownFilled,
  ArrowShortLeftFilled,
  ArrowShortRightFilled,
  ArrowShortUpFilled,
  AttachmentFilled,
  BioGroupFilled,
  BioflowFilled,
  BroomFilled,
  BugFilled,
  CalendarFilled,
  CameraFilled,
  CategoryFilled,
  ChartBarFilled,
  ChartPieFilled,
  CheckMarkInShapeFilled,
  CheckmarkFilled,
  ClinicFilled,
  ClockFilled,
  CloseFilled,
  CloudSyncFilled,
  CloudUploadFilled,
  CompressFilled,
  CopyFilled,
  DesktopFilled,
  DisorderFilled,
  DocFilled,
  DurationFilled,
  EditFilled,
  EvaluationStateFilled,
  ExpandFilled,
  FacebookFilled,
  FileAddFilled,
  FileDownloadFilled,
  FileFailFilled,
  FileFilled,
  FileUploadFilled,
  FilterFilled,
  FoihelseFilled,
  FolderFilled,
  FormFilled,
  GoogleColoredFilled,
  GoogleFilled,
  HeartFilled,
  HideFilled,
  HistoryFilled,
  HomeFilled,
  ImageFilled,
  InstagramFilled,
  InvoiceFilled,
  LinkExternalFilled,
  LinkFilled,
  LinkedInFilled,
  LoadingFilled,
  LocationFilled,
  LockFilled,
  LoginFilled,
  LogoutFilled,
  MailFilled,
  MenuFilled,
  MenuHorizontalFilled,
  MenuVerticalFilled,
  MessageFilled,
  MessageSendFilled,
  MicrophoneOffFilled,
  MicrophoneOnFilled,
  MinusFilled,
  NotificationFilled,
  PackageFilled,
  PasswordFilled,
  PasswordKeyFilled,
  PatientAddFilled,
  PatientFilled,
  PatientsFilled,
  PauseFilled,
  PhoneCallMissedFilled,
  PhoneCallMuttedFilled,
  PhoneCallingFilled,
  PhoneFilled,
  PlayFilled,
  PlayInShapeFilled,
  PlusFilled,
  PlusInShapeFilled,
  PrinterFilled,
  ScaleFilled,
  SearchFilled,
  SendFilled,
  SettingsFilled,
  ShieldDDosFilled,
  ShieldFilled,
  ShowFilled,
  StarFilled,
  StudyFilled,
  TherapistAddFilled,
  TherapistFilled,
  Ticket1Filled,
  Ticket2Filled,
  TranslationFilled,
  TrashFilled,
  UnlockFilled,
  VideoAddFilled,
  VideoOffFilled,
  VideoOnFilled,
  VippsFilled,
  VolumeDownFilled,
  VolumeOffFilled,
  VolumeUpFilled,
  WalletFilled,
  WindowsFilled,
  DoubleCheckmarkFilled
} from '../components/SvgComponentsFilled'

import { PlusOutlined } from '../components/SvgComponentsOutline'
import React from 'react'

const ICONS_NAMES = {
  ActivitiesFilled: <ActivitiesFilled />,
  AlertCircleFilled: <AlertCircleFilled />,
  AlertDangerWarningFilled: <AlertDangerWarningFilled />,
  AlertInfoFilled: <AlertInfoFilled />,
  AppleFilled: <AppleFilled />,
  AppointmentFilled: <AppointmentFilled />,
  ArrowLongDownFilled: <ArrowLongDownFilled />,
  ArrowLongLeftFilled: <ArrowLongLeftFilled />,
  ArrowLongRightFilled: <ArrowLongRightFilled />,
  ArrowLongUpFilled: <ArrowLongUpFilled />,
  ArrowShortDownFilled: <ArrowShortDownFilled />,
  ArrowShortLeftFilled: <ArrowShortLeftFilled />,
  ArrowShortRightFilled: <ArrowShortRightFilled />,
  ArrowShortUpFilled: <ArrowShortUpFilled />,
  AttachmentFilled: <AttachmentFilled />,
  BioflowFilled: <BioflowFilled />,
  BioGroupFilled: <BioGroupFilled />,
  BugFilled: <BugFilled />,
  BroomFilled: <BroomFilled />,
  CalendarFilled: <CalendarFilled />,
  CameraFilled: <CameraFilled />,
  CategoryFilled: <CategoryFilled />,
  ChartBarFilled: <ChartBarFilled />,
  ChartPieFilled: <ChartPieFilled />,
  CheckmarkFilled: <CheckmarkFilled />,
  CheckMarkInShapeFilled: <CheckMarkInShapeFilled />,
  ClinicFilled: <ClinicFilled />,
  ClockFilled: <ClockFilled />,
  CloseFilled: <CloseFilled />,
  CompressFilled: <CompressFilled />,
  CopyFilled: <CopyFilled />,
  CloudSyncFilled: <CloudSyncFilled />,
  CloudUploadFilled: <CloudUploadFilled />,
  DesktopFilled: <DesktopFilled />,
  DisorderFilled: <DisorderFilled />,
  DocFilled: <DocFilled />,
  DoubleCheckmarkFilled: <DoubleCheckmarkFilled />,
  DurationFilled: <DurationFilled />,
  EditFilled: <EditFilled />,
  EvaluationStateFilled: <EvaluationStateFilled />,
  ExpandFilled: <ExpandFilled />,
  FacebookFilled: <FacebookFilled />,
  FileFilled: <FileFilled />,
  FileAddFilled: <FileAddFilled />,
  FileDownloadFilled: <FileDownloadFilled />,
  FileFailFilled: <FileFailFilled />,
  FileUploadFilled: <FileUploadFilled />,
  FilterFilled: <FilterFilled />,
  FoihelseFilled: <FoihelseFilled />,
  FolderFilled: <FolderFilled />,
  FormFilled: <FormFilled />,
  GoogleFilled: <GoogleFilled />,
  GoogleColoredFilled: <GoogleColoredFilled />,
  HeartFilled: <HeartFilled />,
  HideFilled: <HideFilled />,
  HistoryFilled: <HistoryFilled />,
  HomeFilled: <HomeFilled />,
  ImageFilled: <ImageFilled />,
  InstagramFilled: <InstagramFilled />,
  InvoiceFilled: <InvoiceFilled />,
  LinkFilled: <LinkFilled />,
  LinkedInFilled: <LinkedInFilled />,
  LinkExternalFilled: <LinkExternalFilled />,
  LoadingFilled: <LoadingFilled />,
  LocationFilled: <LocationFilled />,
  LockFilled: <LockFilled />,
  LoginFilled: <LoginFilled />,
  LogoutFilled: <LogoutFilled />,
  MailFilled: <MailFilled />,
  MenuFilled: <MenuFilled />,
  MenuHorizontalFilled: <MenuHorizontalFilled />,
  MenuVerticalFilled: <MenuVerticalFilled />,
  MessageFilled: <MessageFilled />,
  MessageSendFilled: <MessageSendFilled />,
  MicrophoneOffFilled: <MicrophoneOffFilled />,
  MicrophoneOnFilled: <MicrophoneOnFilled />,
  MinusFilled: <MinusFilled />,
  NotificationFilled: <NotificationFilled />,
  PackageFilled: <PackageFilled />,
  PasswordFilled: <PasswordFilled />,
  PasswordKeyFilled: <PasswordKeyFilled />,
  PatientFilled: <PatientFilled />,
  PatientAddFilled: <PatientAddFilled />,
  PatientsFilled: <PatientsFilled />,
  PauseFilled: <PauseFilled />,
  PhoneFilled: <PhoneFilled />,
  PhoneCallingFilled: <PhoneCallingFilled />,
  PhoneCallMissedFilled: <PhoneCallMissedFilled />,
  PhoneCallMuttedFilled: <PhoneCallMuttedFilled />,
  PlayFilled: <PlayFilled />,
  PlayInShapeFilled: <PlayInShapeFilled />,
  PlusFilled: <PlusFilled />,
  PlusInShapeFilled: <PlusInShapeFilled />,
  PrinterFilled: <PrinterFilled />,
  ScaleFilled: <ScaleFilled />,
  SearchFilled: <SearchFilled />,
  SendFilled: <SendFilled />,
  SettingsFilled: <SettingsFilled />,
  ShieldFilled: <ShieldFilled />,
  ShieldDDosFilled: <ShieldDDosFilled />,
  ShowFilled: <ShowFilled />,
  StarFilled: <StarFilled />,
  StudyFilled: <StudyFilled />,
  TherapistFilled: <TherapistFilled />,
  TherapistAddFilled: <TherapistAddFilled />,
  Ticket1Filled: <Ticket1Filled />,
  Ticket2Filled: <Ticket2Filled />,
  TranslationFilled: <TranslationFilled />,
  TrashFilled: <TrashFilled />,
  UnlockFilled: <UnlockFilled />,
  VideoOffFilled: <VideoOffFilled />,
  VideoOnFilled: <VideoOnFilled />,
  VideoAddFilled: <VideoAddFilled />,
  VippsFilled: <VippsFilled />,
  VolumeDownFilled: <VolumeDownFilled />,
  VolumeOffFilled: <VolumeOffFilled />,
  VolumeUpFilled: <VolumeUpFilled />,
  WalletFilled: <WalletFilled />,
  WindowsFilled: <WindowsFilled />,
  PlusOutlined: <PlusOutlined />
}

export default ICONS_NAMES
