import {
  AccidentOutlined,
  ActivityHeartOutlined,
  ActivityOutlined,
  AirplayOutlined,
  AirpodsOutlined,
  AlarmClockCheckOutlined,
  AlarmClockMinusOutlined,
  AlarmClockOffOutlined,
  AlarmClockOutlined,
  AlarmClockPlusOutlined,
  AlertCircleOutlined,
  AlertHexagonOutlined,
  AlertOctagonOutlined,
  AlertSquareOutlined,
  AlertTriangleOutlined,
  AlignBottom1Outlined,
  AlignBottom2Outlined,
  AlignCenterOutlined,
  AlignHorizontalCentre1Outlined,
  AlignHorizontalCentre2Outlined,
  AlignJustifyOutlined,
  AlignLeft1Outlined,
  AlignLeft2Outlined,
  AlignLeftOutlined,
  AlignRight1Outlined,
  AlignRight2Outlined,
  AlignRightOutlined,
  AlignTopArrow1Outlined,
  AlignTopArrow2Outlined,
  AlignVerticalCenter1Outlined,
  AlignVerticalCenter2Outlined,
  AnchorOutlined,
  AnnotationAlertOutlined,
  AnnotationCheckOutlined,
  AnnotationDotsOutlined,
  AnnotationHeartOutlined,
  AnnotationInfoOutlined,
  AnnotationOutlined,
  AnnotationPlusOutlined,
  AnnotationQuestionOutlined,
  AnnotationXOutlined,
  Announcement1Outlined,
  Announcement2Outlined,
  Announcement3Outlined,
  AppleOutlined,
  ArchiveOutlined,
  ArrowBlockDownOutlined,
  ArrowBlockLeftOutlined,
  ArrowBlockRightOutlined,
  ArrowBlockUpOutlined,
  ArrowCircleBrokenDownLeftOutlined,
  ArrowCircleBrokenDownOutlined,
  ArrowCircleBrokenDownRightOutlined,
  ArrowCircleBrokenLeftOutlined,
  ArrowCircleBrokenRightOutlined,
  ArrowCircleBrokenUpLeftOutlined,
  ArrowCircleBrokenUpOutlined,
  ArrowCircleBrokenUpRightOutlined,
  ArrowCircleDownLeftOutlined,
  ArrowCircleDownOutlined,
  ArrowCircleDownRightOutlined,
  ArrowCircleLeftOutlined,
  ArrowCircleRightOutlined,
  ArrowCircleUpLeftOutlined,
  ArrowCircleUpOutlined,
  ArrowCircleUpRightOutlined,
  ArrowDownLeftOutlined,
  ArrowDownOutlined,
  ArrowDownRightOutlined,
  ArrowLeftOutlined,
  ArrowNarrowDownLeftOutlined,
  ArrowNarrowDownOutlined,
  ArrowNarrowDownRightOutlined,
  ArrowNarrowLeftOutlined,
  ArrowNarrowRightOutlined,
  ArrowNarrowUpLeftOutlined,
  ArrowNarrowUpOutlined,
  ArrowNarrowUpRightOutlined,
  ArrowRightOutlined,
  ArrowSquareDownLeftOutlined,
  ArrowSquareDownOutlined,
  ArrowSquareDownRightOutlined,
  ArrowSquareLeftOutlined,
  ArrowSquareRightOutlined,
  ArrowSquareUpLeftOutlined,
  ArrowSquareUpOutlined,
  ArrowSquareUpRightOutlined,
  ArrowUpLeftOutlined,
  ArrowUpOutlined,
  ArrowUpRightOutlined,
  ArrowsDownOutlined,
  ArrowsLeftOutlined,
  ArrowsRightOutlined,
  ArrowsTriangleOutlined,
  ArrowsUpOutlined,
  Asterisk1Outlined,
  Asterisk2Outlined,
  AtSignOutlined,
  Atom1Outlined,
  Atom2Outlined,
  Attachment1Outlined,
  Attachment2Outlined,
  Award1Outlined,
  Award2Outlined,
  Award3Outlined,
  Award4Outlined,
  Award5Outlined,
  BackpackOutlined,
  Bank1Outlined,
  Bank2Outlined,
  Bank3Outlined,
  BankNote1Outlined,
  BankNote2Outlined,
  BankNote3Outlined,
  BarChart10Outlined,
  BarChart11Outlined,
  BarChart12Outlined,
  BarChart1Outlined,
  BarChart2Outlined,
  BarChart3Outlined,
  BarChart4Outlined,
  BarChart5Outlined,
  BarChart6Outlined,
  BarChart7Outlined,
  BarChart8Outlined,
  BarChart9Outlined,
  BarChartCircle1Outlined,
  BarChartCircle2Outlined,
  BarChartCircle3Outlined,
  BarChartSquare1Outlined,
  BarChartSquare2Outlined,
  BarChartSquare3Outlined,
  BarChartSquareDownOutlined,
  BarChartSquareMinusOutlined,
  BarChartSquarePlusOutlined,
  BarChartSquareUpOutlined,
  BarLineChartOutlined,
  BatteryCharging1Outlined,
  BatteryCharging2Outlined,
  BatteryEmptyOutlined,
  BatteryFullOutlined,
  BatteryLowOutlined,
  BatteryMidOutlined,
  Beaker1Outlined,
  Beaker2Outlined,
  Bell1Outlined,
  Bell2Outlined,
  Bell3Outlined,
  Bell4Outlined,
  BellMinusOutlined,
  BellOff1Outlined,
  BellOff2Outlined,
  BellOff3Outlined,
  BellPlusOutlined,
  BellRinging1Outlined,
  BellRinging2Outlined,
  BellRinging3Outlined,
  BellRinging4Outlined,
  BezierCurve1Outlined,
  BezierCurve2Outlined,
  BezierCurve3Outlined,
  BluetoothConnectOutlined,
  BluetoothOnOutlined,
  BluetoothOutlined,
  BluetoothSignalOutlined,
  Bold1Outlined,
  Bold2Outlined,
  BoldSquareOutlined,
  BookClosedOutlined,
  BookOpen1Outlined,
  BookOpen2Outlined,
  BookmarkAddOutlined,
  BookmarkCheckOutlined,
  BookmarkMinusOutlined,
  BookmarkOutlined,
  BookmarkXOutlined,
  BottleOutlined,
  BoxOutlined,
  BracketsCheckOutlined,
  BracketsEllipsesOutlined,
  BracketsMinusOutlined,
  BracketsOutlined,
  BracketsPlusOutlined,
  BracketsSlashOutlined,
  BracketsXOutlined,
  Briefcase1Outlined,
  Briefcase2Outlined,
  BrowserOutlined,
  Brush1Outlined,
  Brush2Outlined,
  Brush3Outlined,
  Building1Outlined,
  Building2Outlined,
  Building3Outlined,
  Building4Outlined,
  Building5Outlined,
  Building6Outlined,
  BusOutlined,
  CakeOutlined,
  CalculatorOutlined,
  CalendarCheck1Outlined,
  CalendarCheck2Outlined,
  CalendarDateOutlined,
  CalendarHeart1Outlined,
  CalendarHeart2Outlined,
  CalendarMinus1Outlined,
  CalendarMinus2Outlined,
  CalendarOutlined,
  CalendarPlus1Outlined,
  CalendarPlus2Outlined,
  Camera1Outlined,
  Camera2Outlined,
  Camera3Outlined,
  CameraLensOutlined,
  CameraOffOutlined,
  CameraPlusOutlined,
  Car1Outlined,
  Car2Outlined,
  CarOutlined,
  Certificate1Outlined,
  Certificate2Outlined,
  ChartBreakoutCircleOutlined,
  ChartBreakoutSquareOutlined,
  CheckCircleBrokenOutlined,
  CheckCircleOutlined,
  CheckDone1Outlined,
  CheckDone2Outlined,
  CheckHeartOutlined,
  CheckOutlined,
  CheckSquareBrokenOutlined,
  CheckSquareOutlined,
  CheckVerified1Outlined,
  CheckVerified2Outlined,
  CheckVerified3Outlined,
  ChevronDownDoubleOutlined,
  ChevronDownOutlined,
  ChevronLeftDoubleOutlined,
  ChevronLeftOutlined,
  ChevronRightDoubleOutlined,
  ChevronRightOutlined,
  ChevronSelectorHorizontalOutlined,
  ChevronSelectorVerticalOutlined,
  ChevronUpDoubleOutlined,
  ChevronUpOutlined,
  ChromeCastOutlined,
  CircleCutOutlined,
  CircleOutlined,
  ClapperboardOutlined,
  ClipboardAttachmentOutlined,
  ClipboardCheckOutlined,
  ClipboardDownloadOutlined,
  ClipboardMinusOutlined,
  ClipboardOutlined,
  ClipboardPlusOutlined,
  ClipboardXOutlined,
  ClocheOutlined,
  ClockCheckOutlined,
  ClockFastForwardOutlined,
  ClockOutlined,
  ClockPlusOutlined,
  ClockRefreshOutlined,
  ClockRewindOutlined,
  ClockSnoozeOutlined,
  ClockStopwatchOutlined,
  Cloud1Outlined,
  Cloud2Outlined,
  Cloud3Outlined,
  CloudBlank1Outlined,
  CloudBlank2Outlined,
  CloudLightningOutlined,
  CloudMoonOutlined,
  CloudOffOutlined,
  CloudRaining1Outlined,
  CloudRaining2Outlined,
  CloudRaining3Outlined,
  CloudRaining4Outlined,
  CloudRaining5Outlined,
  CloudRaining6Outlined,
  CloudSnowing1Outlined,
  CloudSnowing2Outlined,
  CloudSun1Outlined,
  CloudSun2Outlined,
  CloudSun3Outlined,
  Code1Outlined,
  Code2Outlined,
  CodeBrowserOutlined,
  CodeCircle1Outlined,
  CodeCircle2Outlined,
  CodeCircle3Outlined,
  CodeSnippet1Outlined,
  CodeSnippet2Outlined,
  CodeSquare1Outlined,
  CodeSquare2Outlined,
  CodepenOutlined,
  CoffeeCupOutlined,
  Coins1Outlined,
  Coins2Outlined,
  Coins3Outlined,
  Coins4Outlined,
  CoinsHandOutlined,
  CoinsStacked1Outlined,
  CoinsStacked2Outlined,
  CoinsStacked3Outlined,
  CoinsStacked4Outlined,
  CoinsSwap1Outlined,
  CoinsSwap2Outlined,
  Colors1Outlined,
  ColorsOutlined,
  Columns2Outlined,
  Columns3Outlined,
  CommandOutlined,
  Compass1Outlined,
  Compass2Outlined,
  Compass3Outlined,
  CompassOutlined,
  ContainerOutlined,
  Contrast1Outlined,
  Contrast2Outlined,
  Contrast3Outlined,
  CookieOutlined,
  Copy1Outlined,
  Copy2Outlined,
  Copy3Outlined,
  Copy4Outlined,
  Copy5Outlined,
  Copy6Outlined,
  Copy7Outlined,
  CornerDownLeftOutlined,
  CornerDownRightOutlined,
  CornerLeftDownOutlined,
  CornerLeftUpOutlined,
  CornerRightDownOutlined,
  CornerRightUpOutlined,
  CornerUpLeftOutlined,
  CornerUpRightOutlined,
  CpuChip1Outlined,
  CpuChip2Outlined,
  CreditCard1Outlined,
  CreditCard2Outlined,
  CreditCardCheckOutlined,
  CreditCardDownOutlined,
  CreditCardDownloadOutlined,
  CreditCardEditOutlined,
  CreditCardLockOutlined,
  CreditCardMinusOutlined,
  CreditCardPlusOutlined,
  CreditCardRefreshOutlined,
  CreditCardSearchOutlined,
  CreditCardShieldOutlined,
  CreditCardUpOutlined,
  CreditCardUploadOutlined,
  CreditCardXOutlined,
  Crop1Outlined,
  Crop2Outlined,
  Cryptocurrency1Outlined,
  Cryptocurrency2Outlined,
  Cryptocurrency3Outlined,
  Cryptocurrency4Outlined,
  Cube1Outlined,
  Cube2Outlined,
  Cube3Outlined,
  Cube4Outlined,
  CubeOutlineOutlined,
  CupcakeOutlined,
  CurrencyBitcoinCircleOutlined,
  CurrencyBitcoinOutlined,
  CurrencyDollarCircleOutlined,
  CurrencyDollarOutlined,
  CurrencyEthereumCircleOutlined,
  CurrencyEthereumOutlined,
  CurrencyEuroCircleOutlined,
  CurrencyEuroOutlined,
  CurrencyPoundCircleOutlined,
  CurrencyPoundOutlined,
  CurrencyRubleCircleOutlined,
  CurrencyRubleOutlined,
  CurrencyRupeeCircleOutlined,
  CurrencyRupeeOutlined,
  CurrencyYenCircleOutlined,
  CurrencyYenOutlined,
  Cursor1Outlined,
  Cursor2Outlined,
  Cursor3Outlined,
  Cursor4Outlined,
  CursorBoxOutlined,
  CursorClick1Outlined,
  CursorClick2Outlined,
  Dashboard2Outlined,
  DashboardOutlined,
  DataOutlined,
  Database1Outlined,
  Database2Outlined,
  Database3Outlined,
  Dataflow1Outlined,
  Dataflow2Outlined,
  Dataflow3Outlined,
  Dataflow4Outlined,
  DeleteOutlined,
  Diamond1Outlined,
  Diamond2Outlined,
  Dice1Outlined,
  Dice2Outlined,
  Dice3Outlined,
  Dice4Outlined,
  Dice5Outlined,
  Dice6Outlined,
  Disc1Outlined,
  Disc2Outlined,
  DistributeSpacingHorizontalOutlined,
  DistributeSpacingVerticalOutlined,
  Divide1Outlined,
  Divide2Outlined,
  Divide3Outlined,
  DividerOutlined,
  Dotpoints1Outlined,
  Dotpoints2Outlined,
  DotsGridOutlined,
  DotsHorizontalOutlined,
  DotsVerticalOutlined,
  Download1Outlined,
  Download2Outlined,
  Download3Outlined,
  Download4Outlined,
  DownloadCloud1Outlined,
  DownloadCloud2Outlined,
  DraggerOutlined,
  DropOutlined,
  Droplets1Outlined,
  Droplets2Outlined,
  Droplets3Outlined,
  DropperOutlined,
  Edit1Outlined,
  Edit2Outlined,
  Edit3Outlined,
  Edit4Outlined,
  Edit5Outlined,
  EggOutlined,
  EqualNotOutlined,
  EqualOutlined,
  EraserOutlined,
  Expand1Outlined,
  Expand2Outlined,
  Expand3Outlined,
  Expand4Outlined,
  Expand5Outlined,
  Expand6Outlined,
  EyeOffOutlined,
  EyeOutlined,
  FaceContentOutlined,
  FaceFrownOutlined,
  FaceHappyOutlined,
  FaceIdOutlined,
  FaceIdSquareOutlined,
  FaceNeutralOutlined,
  FaceSadOutlined,
  FaceSmileOutlined,
  FaceWinkOutlined,
  FacebookOutlined,
  FastBackwardOutlined,
  FastForwardOutlined,
  FeatherOutlined,
  FemaleOutlined,
  FigmaOutlined,
  File1Outlined,
  File2Outlined,
  File3Outlined,
  File4Outlined,
  File5Outlined,
  File6Outlined,
  File7Outlined,
  FileAttachment1Outlined,
  FileAttachment2Outlined,
  FileAttachment3Outlined,
  FileAttachment4Outlined,
  FileAttachment5Outlined,
  FileCheck1Outlined,
  FileCheck2Outlined,
  FileCheck3Outlined,
  FileCode1Outlined,
  FileCode2Outlined,
  FileDownload1Outlined,
  FileDownload2Outlined,
  FileDownload3Outlined,
  FileHeart1Outlined,
  FileHeart2Outlined,
  FileHeart3Outlined,
  FileLock1Outlined,
  FileLock2Outlined,
  FileLock3Outlined,
  FileMinus1Outlined,
  FileMinus2Outlined,
  FileMinus3Outlined,
  FilePlus1Outlined,
  FilePlus2Outlined,
  FilePlus3Outlined,
  FileQuestion1Outlined,
  FileQuestion2Outlined,
  FileQuestion3Outlined,
  FileSearch1Outlined,
  FileSearch2Outlined,
  FileSearch3Outlined,
  FileShield1Outlined,
  FileShield2Outlined,
  FileShield3Outlined,
  FileUpload3Outlined,
  FileX1Outlined,
  FileX2Outlined,
  FileX3Outlined,
  Film1Outlined,
  Film2Outlined,
  Film3Outlined,
  FilterFunnel1Outlined,
  FilterFunnel2Outlined,
  FilterLinesOutlined,
  Fingerprint1Outlined,
  Fingerprint2Outlined,
  Fingerprint3Outlined,
  Fingerprint4Outlined,
  FishOutlined,
  Flag1Outlined,
  Flag2Outlined,
  Flag3Outlined,
  Flag4Outlined,
  Flag5Outlined,
  Flag6Outlined,
  FlashOffOutlined,
  FlashOutlined,
  FlexAlignBottomOutlined,
  FlexAlignLeftOutlined,
  FlexAlignRightOutlined,
  FlexAlignTopOutlined,
  FlipBackwardOutlined,
  FlipForwardOutlined,
  FolderCheckOutlined,
  FolderClosedOutlined,
  FolderCodeOutlined,
  FolderDownloadOutlined,
  FolderLockOutlined,
  FolderMinusOutlined,
  FolderOutlined,
  FolderPlusOutlined,
  FolderQuestionOutlined,
  FolderSearchOutlined,
  FolderShieldOutlined,
  FolderXOutlined,
  ForkKnifeCrossedOutlined,
  ForkKnifeOutlined,
  ForkSpoonCrossedOutlined,
  ForkSpoonOutlined,
  FramerOutlined,
  FuelStationOutlined,
  GamingPad1Outlined,
  GamingPad2Outlined,
  Gift1Outlined,
  Gift2Outlined,
  GitBranch1Outlined,
  GitBranch2Outlined,
  GitCommitOutlined,
  GitMergeOutlined,
  GitPullRequestOutlined,
  Glass1Outlined,
  Glass2Outlined,
  Glasses1Outlined,
  Glasses2Outlined,
  Globe11Outlined,
  Globe1Outlined,
  Globe21Outlined,
  Globe2Outlined,
  Globe3Outlined,
  Globe4Outlined,
  Globe5Outlined,
  Globe6Outlined,
  Google1Outlined,
  GoogleChromeOutlined,
  GraduationHat1Outlined,
  GraduationHat2Outlined,
  Grid1Outlined,
  Grid2Outlined,
  Grid3Outlined,
  GridDotsBlankOutlined,
  GridDotsBottomOutlined,
  GridDotsHorizontalCenterOutlined,
  GridDotsLeftOutlined,
  GridDotsOuterOutlined,
  GridDotsRightOutlined,
  GridDotsTopOutlined,
  GridDotsVerticalCenterOutlined,
  GridOutlined,
  HamburgerOutlined,
  HandOutlined,
  HardDriveOutlined,
  Hash1Outlined,
  Hash2Outlined,
  Heading1Outlined,
  Heading2Outlined,
  HeadingSquareOutlined,
  Headphones1Outlined,
  Headphones2Outlined,
  HeartCircleOutlined,
  HeartHandOutlined,
  HeartOctagonOutlined,
  HeartOutlined,
  HeartRoundedOutlined,
  HeartSquareOutlined,
  HeartsOutlined,
  HelpCircleOutlined,
  HelpHexagonOutlined,
  HelpOctagon1Outlined,
  HelpOctagonOutlined,
  HelpSquareOutlined,
  Hexagon1Outlined,
  Hexagon2Outlined,
  Home1Outlined,
  Home2Outlined,
  Home3Outlined,
  Home4Outlined,
  Home5Outlined,
  HomeLineOutlined,
  HomeSmileOutlined,
  HorizontalBarChart1Outlined,
  HorizontalBarChart2Outlined,
  HorizontalBarChart3Outlined,
  Hourglass1Outlined,
  Hourglass2Outlined,
  Hourglass3Outlined,
  Hurricane1Outlined,
  Hurricane2Outlined,
  Hurricane3Outlined,
  Image1Outlined,
  Image2Outlined,
  Image3Outlined,
  Image4Outlined,
  Image5Outlined,
  ImageCheckOutlined,
  ImageDownOutlined,
  ImageIndentLeftOutlined,
  ImageIndentRightOutlined,
  ImageLeftOutlined,
  ImagePlusOutlined,
  ImageRightOutlined,
  ImageUpOutlined,
  ImageUserCheckOutlined,
  ImageUserDownOutlined,
  ImageUserLeftOutlined,
  ImageUserOutlined,
  ImageUserPlusOutlined,
  ImageUserRightOutlined,
  ImageUserUpOutlined,
  ImageUserXOutlined,
  ImageXOutlined,
  Inbox1Outlined,
  Inbox2Outlined,
  InfinityOutlined,
  InfoCircleOutlined,
  InfoHexagonOutlined,
  InfoOctagonOutlined,
  InfoSquareOutlined,
  InstagramOutlined,
  IntersectCircleOutlined,
  IntersectSquareOutlined,
  Invalid1Outlined,
  Invalid2Outlined,
  Italic1Outlined,
  Italic2Outlined,
  ItalicSquareOutlined,
  Key1Outlined,
  Key2Outlined,
  Keyboard1Outlined,
  Keyboard2Outlined,
  KnifeOutlined,
  LanguageOutlined,
  Laptop1Outlined,
  Laptop2Outlined,
  LayerSingleOutlined,
  LayersThree1Outlined,
  LayersThree2Outlined,
  LayersTwo1Outlined,
  LayersTwo2Outlined,
  LayoutAlt1Outlined,
  LayoutAlt2Outlined,
  LayoutAlt3Outlined,
  LayoutAlt4Outlined,
  LayoutBottomOutlined,
  LayoutGrid1Outlined,
  LayoutGrid2Outlined,
  LayoutLeftOutlined,
  LayoutRightOutlined,
  LayoutTopOutlined,
  LeftIndent1Outlined,
  LeftIndent2Outlined,
  LetterSpacing1Outlined,
  LetterSpacing2Outlined,
  LifeBuoy1Outlined,
  LifeBuoy2Outlined,
  Lightbulb1Outlined,
  Lightbulb2Outlined,
  Lightbulb3Outlined,
  Lightbulb4Outlined,
  Lightbulb5Outlined,
  Lightning1Outlined,
  Lightning2Outlined,
  LineChartDown1Outlined,
  LineChartDown2Outlined,
  LineChartDown3Outlined,
  LineChartDown4Outlined,
  LineChartDown5Outlined,
  LineChartUp1Outlined,
  LineChartUp2Outlined,
  LineChartUp3Outlined,
  LineChartUp4Outlined,
  LineChartUp5Outlined,
  LineHeightOutlined,
  Link1Outlined,
  Link2Outlined,
  Link3Outlined,
  Link4Outlined,
  Link5Outlined,
  LinkBroken1Outlined,
  LinkBroken2Outlined,
  LinkExternal1Outlined,
  LinkExternal2Outlined,
  LinkedInOutlined,
  ListOutlined,
  Loading1Outlined,
  Loading2Outlined,
  Loading3Outlined,
  Lock1Outlined,
  Lock2Outlined,
  Lock3Outlined,
  Lock4Outlined,
  LockKeyholeCircleOutlined,
  LockKeyholeSquareOutlined,
  LockUnlocked1Outlined,
  LockUnlocked2Outlined,
  LockUnlocked3Outlined,
  LockUnlocked4Outlined,
  LogIn1Outlined,
  LogIn2Outlined,
  LogIn3Outlined,
  LogIn4Outlined,
  LogOut1Outlined,
  LogOut2Outlined,
  LogOut3Outlined,
  LogOut4Outlined,
  Luggage1Outlined,
  Luggage2Outlined,
  Luggage3Outlined,
  MagicWand1Outlined,
  MagicWand2Outlined,
  Mail1Outlined,
  Mail2Outlined,
  Mail3Outlined,
  Mail4Outlined,
  Mail5Outlined,
  MaleOutlined,
  Map1Outlined,
  Map2Outlined,
  MarkOutlined,
  MarkerPin1Outlined,
  MarkerPin2Outlined,
  MarkerPin3Outlined,
  MarkerPin4Outlined,
  MarkerPin5Outlined,
  MarkerPin6Outlined,
  MartiniGlassCrossedOutlined,
  MartiniGlassOutlined,
  Maximize1Outlined,
  Maximize2Outlined,
  MedicalCircleOutlined,
  MedicalCrossOutlined,
  MedicalSquareOutlined,
  Menu1Outlined,
  Menu2Outlined,
  Menu3Outlined,
  Menu4Outlined,
  Menu5Outlined,
  MessageAlertCircleOutlined,
  MessageAlertSquareOutlined,
  MessageChatCircleOutlined,
  MessageChatSquareOutlined,
  MessageCheckCircleOutlined,
  MessageCheckSquareOutlined,
  MessageCircle1Outlined,
  MessageCircle2Outlined,
  MessageDotsCircleOutlined,
  MessageDotsSquareOutlined,
  MessageHeartCircleOutlined,
  MessageHeartSquareOutlined,
  MessageNotificationCircleOutlined,
  MessageNotificationSquare1Outlined,
  MessageNotificationSquareOutlined,
  MessagePlusCircleOutlined,
  MessagePlusSquareOutlined,
  MessageQuestionCircleOutlined,
  MessageQuestionSquareOutlined,
  MessageSmileCircleOutlined,
  MessageSmileSquareOutlined,
  MessageSquare1Outlined,
  MessageSquare2Outlined,
  MessageTextCircle1Outlined,
  MessageTextCircle2Outlined,
  MessageTextSquare1Outlined,
  MessageTextSquare2Outlined,
  MessageXCircleOutlined,
  MessageXSquareOutlined,
  Microphone1Outlined,
  Microphone2Outlined,
  MicrophoneOff1Outlined,
  MicrophoneOff2Outlined,
  MicroscopeOutlined,
  Minimize1Outlined,
  Minimize2Outlined,
  MinusCircleOutlined,
  MinusOutlined,
  MinusSquareOutlined,
  Modem1Outlined,
  Modem2Outlined,
  Monitor1Outlined,
  Monitor2Outlined,
  Monitor3Outlined,
  Monitor4Outlined,
  Monitor5Outlined,
  Moon1Outlined,
  Moon2Outlined,
  MoonEclipseOutlined,
  MoonStarOutlined,
  MopedOutlined,
  MouseOutlined,
  MoveOutlined,
  MugSaucerOutlined,
  MugSaucerSteamOutlined,
  MusicNote1Outlined,
  MusicNote2Outlined,
  MusicOutlined,
  NavigationPointer1Outlined,
  NavigationPointer2Outlined,
  NavigationPointerOff1Outlined,
  NavigationPointerOff2Outlined,
  NonBinaryOutlined,
  NotificationBoxOutlined,
  NotificationTextOutlined,
  OctagonOutlined,
  PackageCheckOutlined,
  PackageMinusOutlined,
  PackageOutlined,
  PackagePlusOutlined,
  PackageSearchOutlined,
  PackageXOutlined,
  PaintOutlined,
  PaintPourOutlined,
  PaletteOutlined,
  PaperclipOutlined,
  ParagraphSpacingOutlined,
  ParagraphWrapOutlined,
  ParkingOutlined,
  PasscodeLockOutlined,
  PasscodeOutlined,
  PassportOutlined,
  PauseCircleOutlined,
  PauseSquareOutlined,
  PenTool1Outlined,
  PenTool2Outlined,
  PenToolMinusOutlined,
  PenToolPlusOutlined,
  Pencil1Outlined,
  Pencil2Outlined,
  PencilLineOutlined,
  PentagonOutlined,
  Percent1Outlined,
  Percent2Outlined,
  Percent3Outlined,
  Perspective1Outlined,
  Perspective2Outlined,
  Phone1Outlined,
  Phone2Outlined,
  PhoneCall1Outlined,
  PhoneCall2Outlined,
  PhoneHangUpOutlined,
  PhoneIncoming1Outlined,
  PhoneIncoming2Outlined,
  PhoneOutgoing1Outlined,
  PhoneOutgoing2Outlined,
  PhoneOutlined,
  PhonePauseOutlined,
  PhonePlusOutlined,
  PhoneXOutlined,
  PieChart1Outlined,
  PieChart2Outlined,
  PieChart3Outlined,
  PieChart4Outlined,
  PiggyBank1Outlined,
  PiggyBank2Outlined,
  Pilcrow1Outlined,
  Pilcrow2Outlined,
  PilcrowSquareOutlined,
  Pin1Outlined,
  Pin2Outlined,
  PizzaOutlined,
  PlaceholderOutlined,
  PlayCircleOutlined,
  PlayOutlined,
  PlaySquareOutlined,
  PlugStationOutlined,
  Plus1Outlined,
  PlusCircleOutlined,
  PlusOutlined,
  PlusSquareOutlined,
  PodcastOutlined,
  PoliceBadgeOutlined,
  PopcornOutlined,
  Power1Outlined,
  Power2Outlined,
  Power3Outlined,
  PresentationChart1Outlined,
  PresentationChart2Outlined,
  PresentationChart3Outlined,
  PrinterOutlined,
  PuzzlePiece2Outlined,
  PuzzlePieceOutlined,
  QrCode1Outlined,
  QrCode2Outlined,
  ReceiptCheckOutlined,
  ReceiptOutlined,
  Recording1Outlined,
  Recording2Outlined,
  Recording3Outlined,
  Reflect1Outlined,
  Reflect2Outlined,
  RefreshCcw1Outlined,
  RefreshCcw2Outlined,
  RefreshCcw3Outlined,
  RefreshCcw4Outlined,
  RefreshCcw5Outlined,
  RefreshCw1Outlined,
  RefreshCw2Outlined,
  RefreshCw3Outlined,
  RefreshCw4Outlined,
  RefreshCw5Outlined,
  Repeat1Outlined,
  Repeat2Outlined,
  Repeat3Outlined,
  Repeat4Outlined,
  RestaurantMenuOutlined,
  ReverseLeftOutlined,
  ReverseRightOutlined,
  RightIndent1Outlined,
  RightIndent2Outlined,
  RoadSignOutlined,
  RoadWorksOutlined,
  Rocket1Outlined,
  Rocket2Outlined,
  RollerBrushOutlined,
  RouteOutlined,
  Rows1Outlined,
  Rows2Outlined,
  Rows3Outlined,
  Rss1Outlined,
  Rss2Outlined,
  RulerOutlined,
  SafeOutlined,
  Sale1Outlined,
  Sale2Outlined,
  Sale3Outlined,
  Sale4Outlined,
  Save1Outlined,
  Save2Outlined,
  Save3Outlined,
  Scale1Outlined,
  Scale2Outlined,
  Scale3Outlined,
  Scales1Outlined,
  Scales2Outlined,
  ScanOutlined,
  Scissors1Outlined,
  Scissors2Outlined,
  ScissorsCut1Outlined,
  ScissorsCut2Outlined,
  SearchLgOutlined,
  SearchMdOutlined,
  SearchRefractionOutlined,
  SearchSmOutlined,
  Send1Outlined,
  Send2Outlined,
  Send3Outlined,
  Server1Outlined,
  Server2Outlined,
  Server3Outlined,
  Server4Outlined,
  Server5Outlined,
  Server6Outlined,
  Settings1Outlined,
  Settings2Outlined,
  Settings3Outlined,
  Settings4Outlined,
  Share1Outlined,
  Share2Outlined,
  Share3Outlined,
  Share4Outlined,
  Share5Outlined,
  Share6Outlined,
  Share7Outlined,
  Shield1Outlined,
  Shield2Outlined,
  Shield3Outlined,
  ShieldDollarOutlined,
  ShieldOffOutlined,
  ShieldPlusOutlined,
  ShieldTickOutlined,
  ShieldZapOutlined,
  ShipOutlined,
  ShoppingBag1Outlined,
  ShoppingBag2Outlined,
  ShoppingBag3Outlined,
  ShoppingCart1Outlined,
  ShoppingCart2Outlined,
  ShoppingCart3Outlined,
  Shuffle1Outlined,
  Shuffle2Outlined,
  SignBothOutlined,
  SignLeftOutlined,
  SignRightOutlined,
  Signal1OffOutlined,
  Signal1Outlined,
  Signal2OffOutlined,
  Signal2Outlined,
  Signal3Outlined,
  SimcardOutlined,
  SkewOutlined,
  SkipBackOutlined,
  SkipForwardOutlined,
  SlashCircle1Outlined,
  SlashCircle2Outlined,
  SlashDividerOutlined,
  SlashOctagonOutlined,
  Sliders1Outlined,
  Sliders2Outlined,
  Sliders3Outlined,
  Sliders4Outlined,
  Snowflake1Outlined,
  Snowflake2Outlined,
  SortDownAlphabetAscOutlined,
  SortDownAlphabetDescOutlined,
  SortDownBlockAscOutlined,
  SortDownBlockDescOutlined,
  SortDownLineAscOutlined,
  SortDownLineDescOutlined,
  SortDownNumberAscOutlined,
  SortDownNumberDescOutlined,
  SortUpAlphabetAscOutlined,
  SortUpAlphabetDescOutlined,
  SortUpBlockAscOutlined,
  SortUpBlockDescOutlined,
  SortUpLineAscOutlined,
  SortUpLineDescOutlined,
  SortUpNumberAscOutlined,
  SortUpNumberDescOutlined,
  SpacingHeight1Outlined,
  SpacingHeight2Outlined,
  SpacingWidth1Outlined,
  SpacingWidth2Outlined,
  Speaker1Outlined,
  Speaker2Outlined,
  Speaker3Outlined,
  Speedometer1Outlined,
  Speedometer2Outlined,
  Speedometer3Outlined,
  Speedometer4Outlined,
  SquareOutlined,
  StandOutlined,
  Star1Outlined,
  Star2Outlined,
  Star3Outlined,
  Star4Outlined,
  Star5Outlined,
  Star6Outlined,
  Star7Outlined,
  Stars1Outlined,
  Stars2Outlined,
  Stars3Outlined,
  StickerCircleOutlined,
  StickerSquareOutlined,
  StopCircleOutlined,
  StopOutlined,
  StopSquareOutlined,
  StoreOutlined,
  Strikethrough1Outlined,
  Strikethrough2Outlined,
  StrikethroughSquareOutlined,
  SubscriptOutlined,
  SunOutlined,
  SunSetting1Outlined,
  SunSetting2Outlined,
  SunSetting3Outlined,
  SunriseOutlined,
  SunsetOutlined,
  SwitchHorizontal1Outlined,
  SwitchHorizontal2Outlined,
  SwitchVertical1Outlined,
  SwitchVertical2Outlined,
  TableOutlined,
  Tablet1Outlined,
  Tablet2Outlined,
  Tag1Outlined,
  Tag2Outlined,
  Tag3Outlined,
  Target1Outlined,
  Target2Outlined,
  Target3Outlined,
  Target4Outlined,
  Target5Outlined,
  TelescopeOutlined,
  TerminalBrowserOutlined,
  TerminalCircleOutlined,
  TerminalOutlined,
  TerminalSquareOutlined,
  TextInputOutlined,
  Thermometer1Outlined,
  Thermometer2Outlined,
  Thermometer3Outlined,
  ThermometerColdOutlined,
  ThermometerWarmOutlined,
  ThumbsDownOutlined,
  ThumbsUpOutlined,
  Ticket1Outlined,
  Ticket2Outlined,
  Toggle1LeftOutlined,
  Toggle1RightOutlined,
  Toggle2LeftOutlined,
  Toggle2RightOutlined,
  Toggle3LeftOutlined,
  Toggle3RightOutlined,
  Tool1Outlined,
  Tool2Outlined,
  TrafficCone1Outlined,
  TrafficCone2Outlined,
  TrafficJamOutlined,
  TrainOutlined,
  TramOutlined,
  TransformOutlined,
  Translate1Outlined,
  Translate2Outlined,
  Trash1Outlined,
  Trash2Outlined,
  Trash3Outlined,
  Trash4Outlined,
  TrendDown1Outlined,
  TrendDown2Outlined,
  TrendUp1Outlined,
  TrendUp2Outlined,
  TriangleOutlined,
  Trophy1Outlined,
  Trophy2Outlined,
  Truck1Outlined,
  Truck2Outlined,
  Tv1Outlined,
  Tv2Outlined,
  Tv3Outlined,
  Twitter1Outlined,
  Type1Outlined,
  Type2Outlined,
  TypeSquareOutlined,
  TypeStrikethrough1Outlined,
  TypeStrikethrough2Outlined,
  Umbrella1Outlined,
  Umbrella2Outlined,
  Umbrella3Outlined,
  Underline1Outlined,
  Underline2Outlined,
  UnderlineSquareOutlined,
  Upload1Outlined,
  Upload2Outlined,
  Upload3Outlined,
  Upload4Outlined,
  UploadCloud1Outlined,
  UploadCloud2Outlined,
  UsbFlashDriveOutlined,
  User1Outlined,
  User2Outlined,
  User3Outlined,
  UserSleepOutlined,
  UserCheck1Outlined,
  UserCheck2Outlined,
  UserCircleOutlined,
  UserDown1Outlined,
  UserDown2Outlined,
  UserEditOutlined,
  UserLeft1Outlined,
  UserLeft2Outlined,
  UserMinus1Outlined,
  UserMinus2Outlined,
  UserPlus1Outlined,
  UserPlus2Outlined,
  UserRight1Outlined,
  UserRight2Outlined,
  UserSquareOutlined,
  UserUp1Outlined,
  UserUp2Outlined,
  UserX1Outlined,
  UserX2Outlined,
  Users1Outlined,
  Users2Outlined,
  Users3Outlined,
  UsersCheckOutlined,
  UsersDownOutlined,
  UsersEditOutlined,
  UsersLeftOutlined,
  UsersMinusOutlined,
  UsersPlusOutlined,
  UsersRightOutlined,
  UsersUpOutlined,
  UsersXOutlined,
  VariableOutlined,
  VideoRecorderOffOutlined,
  VideoRecorderOutlined,
  VippsOutlined,
  VirusOutlined,
  VoicemailOutlined,
  VolumeMaxOutlined,
  VolumeMinOutlined,
  VolumeMinusOutlined,
  VolumePlusOutlined,
  VolumeXOutlined,
  Wallet1Outlined,
  Wallet2Outlined,
  Wallet3Outlined,
  Wallet4Outlined,
  Wallet5Outlined,
  WatchCircleOutlined,
  WatchSquareOutlined,
  WavesOutlined,
  Webcam1Outlined,
  Webcam2Outlined,
  WifiOffOutlined,
  WifiOutlined,
  Wind1Outlined,
  Wind2Outlined,
  Wind3Outlined,
  WindowsOutlined,
  WineGlassOutlined,
  XCircleOutlined,
  XCloseOutlined,
  XOutlined,
  XSquareOutlined,
  YoutubeOutlined,
  ZapCircleOutlined,
  ZapFastOutlined,
  ZapOffOutlined,
  ZapOutlined,
  ZapSquareOutlined,
  ZoomInOutlined,
  ZoomOutOutlined
} from '../components/SvgComponentsOutline'
import {
  ActivitiesFilled,
  AlertCircleFilled,
  AlertDangerWarningFilled,
  AlertInfoFilled,
  AppleFilled,
  AppointmentFilled,
  ArrowLongDownFilled,
  ArrowLongLeftFilled,
  ArrowLongRightFilled,
  ArrowLongUpFilled,
  ArrowShortDownFilled,
  ArrowShortLeftFilled,
  ArrowShortRightFilled,
  ArrowShortUpFilled,
  AttachmentFilled,
  BioGroupFilled,
  BioflowFilled,
  BroomFilled,
  BugFilled,
  CalendarFilled,
  CameraFilled,
  CategoryFilled,
  ChartBarFilled,
  ChartPieFilled,
  CheckMarkInShapeFilled,
  CheckVerified2Filled,
  CheckmarkFilled,
  ClinicFilled,
  ClockFilled,
  CloseFilled,
  CloudSyncFilled,
  CloudUploadFilled,
  CompressFilled,
  CopyFilled,
  DesktopFilled,
  DisorderFilled,
  DocFilled,
  DoubleCheckmarkFilled,
  DurationFilled,
  EditFilled,
  EvaluationStateFilled,
  ExpandFilled,
  FacebookFilled,
  FileAddFilled,
  FileDownloadFilled,
  FileFailFilled,
  FileFilled,
  FileUploadFilled,
  FilterFilled,
  FoihelseFilled,
  FolderFilled,
  FormFilled,
  GoogleColoredFilled,
  GoogleFilled,
  HeartFilled,
  HideFilled,
  HistoryFilled,
  HomeFilled,
  ImageFilled,
  InstagramFilled,
  InvoiceFilled,
  LinkExternalFilled,
  LinkFilled,
  LinkedInFilled,
  LoadingFilled,
  LocationFilled,
  LockFilled,
  LoginFilled,
  LogoutFilled,
  MailFilled,
  MenuFilled,
  MenuHorizontalFilled,
  MenuVerticalFilled,
  MessageFilled,
  MessageSendFilled,
  MicrophoneOffFilled,
  MicrophoneOnFilled,
  MinusFilled,
  NotificationFilled,
  PackageFilled,
  PasswordFilled,
  PasswordKeyFilled,
  PatientAddFilled,
  PatientFilled,
  PatientsFilled,
  PauseFilled,
  PhoneCallMissedFilled,
  PhoneCallMuttedFilled,
  PhoneCallingFilled,
  PhoneFilled,
  PlayFilled,
  PlayInShapeFilled,
  PlusFilled,
  PlusInShapeFilled,
  PrinterFilled,
  ScaleFilled,
  SearchFilled,
  SendFilled,
  SettingsFilled,
  ShieldDDosFilled,
  ShieldFilled,
  ShowFilled,
  StarFilled,
  StudyFilled,
  TherapistAddFilled,
  TherapistFilled,
  Ticket1Filled,
  Ticket2Filled,
  TranslationFilled,
  TrashFilled,
  UnlockFilled,
  VideoAddFilled,
  VideoOffFilled,
  VideoOnFilled,
  VippsFilled,
  VolumeDownFilled,
  VolumeOffFilled,
  VolumeUpFilled,
  WalletFilled,
  WindowsFilled
} from '../components/SvgComponentsFilled'

import React from 'react'

const ICONS_NAMES = {
  SortDownAlphabetAscOutlined: <SortDownAlphabetAscOutlined />,
  SortDownAlphabetDescOutlined: <SortDownAlphabetDescOutlined />,
  SortDownBlockAscOutlined: <SortDownBlockAscOutlined />,
  SortDownBlockDescOutlined: <SortDownBlockDescOutlined />,
  SortDownLineDescOutlined: <SortDownLineDescOutlined />,
  SortDownNumberAscOutlined: <SortDownNumberAscOutlined />,
  SortDownNumberDescOutlined: <SortDownNumberDescOutlined />,
  SortUpAlphabetAscOutlined: <SortUpAlphabetAscOutlined />,
  SortUpAlphabetDescOutlined: <SortUpAlphabetDescOutlined />,
  SortUpBlockAscOutlined: <SortUpBlockAscOutlined />,
  SortUpBlockDescOutlined: <SortUpBlockDescOutlined />,
  SortUpLineAscOutlined: <SortUpLineAscOutlined />,
  SortUpLineDescOutlined: <SortUpLineDescOutlined />,
  SortUpNumberAscOutlined: <SortUpNumberAscOutlined />,
  SortUpNumberDescOutlined: <SortUpNumberDescOutlined />,
  SortDownLineAscOutlined: <SortDownLineAscOutlined />,
  AccidentOutlined: <AccidentOutlined />,
  PoliceBadgeOutlined: <PoliceBadgeOutlined />,
  RoadWorksOutlined: <RoadWorksOutlined />,
  TrafficCone1Outlined: <TrafficCone1Outlined />,
  TrafficCone2Outlined: <TrafficCone2Outlined />,
  TrafficJamOutlined: <TrafficJamOutlined />,
  ActivitiesFilled: <ActivitiesFilled />,
  AlertCircleFilled: <AlertCircleFilled />,
  AlertDangerWarningFilled: <AlertDangerWarningFilled />,
  AlertInfoFilled: <AlertInfoFilled />,
  AppleFilled: <AppleFilled />,
  AppointmentFilled: <AppointmentFilled />,
  ArrowLongDownFilled: <ArrowLongDownFilled />,
  ArrowLongLeftFilled: <ArrowLongLeftFilled />,
  ArrowLongRightFilled: <ArrowLongRightFilled />,
  ArrowLongUpFilled: <ArrowLongUpFilled />,
  ArrowShortDownFilled: <ArrowShortDownFilled />,
  ArrowShortLeftFilled: <ArrowShortLeftFilled />,
  ArrowShortRightFilled: <ArrowShortRightFilled />,
  ArrowShortUpFilled: <ArrowShortUpFilled />,
  AttachmentFilled: <AttachmentFilled />,
  BioflowFilled: <BioflowFilled />,
  BioGroupFilled: <BioGroupFilled />,
  BugFilled: <BugFilled />,
  BroomFilled: <BroomFilled />,
  CalendarFilled: <CalendarFilled />,
  CameraFilled: <CameraFilled />,
  CategoryFilled: <CategoryFilled />,
  ChartBarFilled: <ChartBarFilled />,
  ChartPieFilled: <ChartPieFilled />,
  CheckmarkFilled: <CheckmarkFilled />,
  CheckMarkInShapeFilled: <CheckMarkInShapeFilled />,
  CheckVerified2Filled: <CheckVerified2Filled />,
  ClinicFilled: <ClinicFilled />,
  ClockFilled: <ClockFilled />,
  CloseFilled: <CloseFilled />,
  CompressFilled: <CompressFilled />,
  CopyFilled: <CopyFilled />,
  CloudSyncFilled: <CloudSyncFilled />,
  CloudUploadFilled: <CloudUploadFilled />,
  DesktopFilled: <DesktopFilled />,
  DisorderFilled: <DisorderFilled />,
  DocFilled: <DocFilled />,
  DoubleCheckmarkFilled: <DoubleCheckmarkFilled />,
  DurationFilled: <DurationFilled />,
  EditFilled: <EditFilled />,
  EvaluationStateFilled: <EvaluationStateFilled />,
  ExpandFilled: <ExpandFilled />,
  FacebookFilled: <FacebookFilled />,
  FileFilled: <FileFilled />,
  FileAddFilled: <FileAddFilled />,
  FileDownloadFilled: <FileDownloadFilled />,
  FileFailFilled: <FileFailFilled />,
  FileUploadFilled: <FileUploadFilled />,
  FilterFilled: <FilterFilled />,
  FoihelseFilled: <FoihelseFilled />,
  FolderFilled: <FolderFilled />,
  FormFilled: <FormFilled />,
  GoogleFilled: <GoogleFilled />,
  GoogleColoredFilled: <GoogleColoredFilled />,
  HeartFilled: <HeartFilled />,
  HideFilled: <HideFilled />,
  HistoryFilled: <HistoryFilled />,
  HomeFilled: <HomeFilled />,
  ImageFilled: <ImageFilled />,
  InstagramFilled: <InstagramFilled />,
  InvoiceFilled: <InvoiceFilled />,
  LinkFilled: <LinkFilled />,
  LinkedInFilled: <LinkedInFilled />,
  LinkExternalFilled: <LinkExternalFilled />,
  LoadingFilled: <LoadingFilled />,
  LocationFilled: <LocationFilled />,
  LockFilled: <LockFilled />,
  LoginFilled: <LoginFilled />,
  LogoutFilled: <LogoutFilled />,
  MailFilled: <MailFilled />,
  MenuFilled: <MenuFilled />,
  MenuHorizontalFilled: <MenuHorizontalFilled />,
  MenuVerticalFilled: <MenuVerticalFilled />,
  MessageFilled: <MessageFilled />,
  MessageSendFilled: <MessageSendFilled />,
  MicrophoneOffFilled: <MicrophoneOffFilled />,
  MicrophoneOnFilled: <MicrophoneOnFilled />,
  MinusFilled: <MinusFilled />,
  NotificationFilled: <NotificationFilled />,
  PackageFilled: <PackageFilled />,
  PasswordFilled: <PasswordFilled />,
  PasswordKeyFilled: <PasswordKeyFilled />,
  PatientFilled: <PatientFilled />,
  PatientAddFilled: <PatientAddFilled />,
  PatientsFilled: <PatientsFilled />,
  PauseFilled: <PauseFilled />,
  PhoneFilled: <PhoneFilled />,
  PhoneCallingFilled: <PhoneCallingFilled />,
  PhoneCallMissedFilled: <PhoneCallMissedFilled />,
  PhoneCallMuttedFilled: <PhoneCallMuttedFilled />,
  PlayFilled: <PlayFilled />,
  PlayInShapeFilled: <PlayInShapeFilled />,
  PlusFilled: <PlusFilled />,
  PlusInShapeFilled: <PlusInShapeFilled />,
  PrinterFilled: <PrinterFilled />,
  ScaleFilled: <ScaleFilled />,
  SearchFilled: <SearchFilled />,
  SendFilled: <SendFilled />,
  SettingsFilled: <SettingsFilled />,
  ShieldFilled: <ShieldFilled />,
  ShieldDDosFilled: <ShieldDDosFilled />,
  ShowFilled: <ShowFilled />,
  StarFilled: <StarFilled />,
  StudyFilled: <StudyFilled />,
  TherapistFilled: <TherapistFilled />,
  TherapistAddFilled: <TherapistAddFilled />,
  Ticket1Filled: <Ticket1Filled />,
  Ticket2Filled: <Ticket2Filled />,
  TranslationFilled: <TranslationFilled />,
  TrashFilled: <TrashFilled />,
  UnlockFilled: <UnlockFilled />,
  VideoOffFilled: <VideoOffFilled />,
  VideoOnFilled: <VideoOnFilled />,
  VideoAddFilled: <VideoAddFilled />,
  VippsFilled: <VippsFilled />,
  VolumeDownFilled: <VolumeDownFilled />,
  VolumeOffFilled: <VolumeOffFilled />,
  VolumeUpFilled: <VolumeUpFilled />,
  WalletFilled: <WalletFilled />,
  WindowsFilled: <WindowsFilled />,
  Plus1Outlined: <Plus1Outlined />,
  LanguageOutlined: <LanguageOutlined />,
  // NEW ICONS COMPONENTS
  AppleOutlined: <AppleOutlined />,
  FacebookOutlined: <FacebookOutlined />,
  Google1Outlined: <Google1Outlined />,
  InstagramOutlined: <InstagramOutlined />,
  LinkedInOutlined: <LinkedInOutlined />,
  VippsOutlined: <VippsOutlined />,
  WindowsOutlined: <WindowsOutlined />,
  ActivityHeartOutlined: <ActivityHeartOutlined />,
  ActivityOutlined: <ActivityOutlined />,
  AirplayOutlined: <AirplayOutlined />,
  AirpodsOutlined: <AirpodsOutlined />,
  AlarmClockCheckOutlined: <AlarmClockCheckOutlined />,
  AlarmClockMinusOutlined: <AlarmClockMinusOutlined />,
  AlarmClockOffOutlined: <AlarmClockOffOutlined />,
  AlarmClockPlusOutlined: <AlarmClockPlusOutlined />,
  AlarmClockOutlined: <AlarmClockOutlined />,
  AlertCircleOutlined: <AlertCircleOutlined />,
  AlertHexagonOutlined: <AlertHexagonOutlined />,
  AlertOctagonOutlined: <AlertOctagonOutlined />,
  AlertSquareOutlined: <AlertSquareOutlined />,
  AlertTriangleOutlined: <AlertTriangleOutlined />,
  AlignBottom1Outlined: <AlignBottom1Outlined />,
  AlignBottom2Outlined: <AlignBottom2Outlined />,
  AlignCenterOutlined: <AlignCenterOutlined />,
  AlignHorizontalCentre1Outlined: <AlignHorizontalCentre1Outlined />,
  AlignHorizontalCentre2Outlined: <AlignHorizontalCentre2Outlined />,
  AlignJustifyOutlined: <AlignJustifyOutlined />,
  AlignLeft1Outlined: <AlignLeft1Outlined />,
  AlignLeft2Outlined: <AlignLeft2Outlined />,
  AlignLeftOutlined: <AlignLeftOutlined />,
  AlignRight1Outlined: <AlignRight1Outlined />,
  AlignRight2Outlined: <AlignRight2Outlined />,
  AlignRightOutlined: <AlignRightOutlined />,
  AlignTopArrow1Outlined: <AlignTopArrow1Outlined />,
  AlignTopArrow2Outlined: <AlignTopArrow2Outlined />,
  AlignVerticalCenter1Outlined: <AlignVerticalCenter1Outlined />,
  AlignVerticalCenter2Outlined: <AlignVerticalCenter2Outlined />,
  AnchorOutlined: <AnchorOutlined />,
  AnnotationAlertOutlined: <AnnotationAlertOutlined />,
  AnnotationCheckOutlined: <AnnotationCheckOutlined />,
  AnnotationDotsOutlined: <AnnotationDotsOutlined />,
  AnnotationHeartOutlined: <AnnotationHeartOutlined />,
  AnnotationInfoOutlined: <AnnotationInfoOutlined />,
  AnnotationPlusOutlined: <AnnotationPlusOutlined />,
  AnnotationQuestionOutlined: <AnnotationQuestionOutlined />,
  AnnotationXOutlined: <AnnotationXOutlined />,
  AnnotationOutlined: <AnnotationOutlined />,
  Announcement1Outlined: <Announcement1Outlined />,
  Announcement2Outlined: <Announcement2Outlined />,
  Announcement3Outlined: <Announcement3Outlined />,
  ArchiveOutlined: <ArchiveOutlined />,
  ArrowBlockDownOutlined: <ArrowBlockDownOutlined />,
  ArrowBlockLeftOutlined: <ArrowBlockLeftOutlined />,
  ArrowBlockRightOutlined: <ArrowBlockRightOutlined />,
  ArrowBlockUpOutlined: <ArrowBlockUpOutlined />,
  ArrowCircleBrokenDownLeftOutlined: <ArrowCircleBrokenDownLeftOutlined />,
  ArrowCircleBrokenDownRightOutlined: <ArrowCircleBrokenDownRightOutlined />,
  ArrowCircleBrokenDownOutlined: <ArrowCircleBrokenDownOutlined />,
  ArrowCircleBrokenLeftOutlined: <ArrowCircleBrokenLeftOutlined />,
  ArrowCircleBrokenRightOutlined: <ArrowCircleBrokenRightOutlined />,
  ArrowCircleBrokenUpLeftOutlined: <ArrowCircleBrokenUpLeftOutlined />,
  ArrowCircleBrokenUpRightOutlined: <ArrowCircleBrokenUpRightOutlined />,
  ArrowCircleBrokenUpOutlined: <ArrowCircleBrokenUpOutlined />,
  ArrowCircleDownLeftOutlined: <ArrowCircleDownLeftOutlined />,
  ArrowCircleDownRightOutlined: <ArrowCircleDownRightOutlined />,
  ArrowCircleDownOutlined: <ArrowCircleDownOutlined />,
  ArrowCircleLeftOutlined: <ArrowCircleLeftOutlined />,
  ArrowCircleRightOutlined: <ArrowCircleRightOutlined />,
  ArrowCircleUpLeftOutlined: <ArrowCircleUpLeftOutlined />,
  ArrowCircleUpRightOutlined: <ArrowCircleUpRightOutlined />,
  ArrowCircleUpOutlined: <ArrowCircleUpOutlined />,
  ArrowDownLeftOutlined: <ArrowDownLeftOutlined />,
  ArrowDownRightOutlined: <ArrowDownRightOutlined />,
  ArrowDownOutlined: <ArrowDownOutlined />,
  ArrowLeftOutlined: <ArrowLeftOutlined />,
  ArrowNarrowDownLeftOutlined: <ArrowNarrowDownLeftOutlined />,
  ArrowNarrowDownRightOutlined: <ArrowNarrowDownRightOutlined />,
  ArrowNarrowDownOutlined: <ArrowNarrowDownOutlined />,
  ArrowNarrowLeftOutlined: <ArrowNarrowLeftOutlined />,
  ArrowNarrowRightOutlined: <ArrowNarrowRightOutlined />,
  ArrowNarrowUpLeftOutlined: <ArrowNarrowUpLeftOutlined />,
  ArrowNarrowUpRightOutlined: <ArrowNarrowUpRightOutlined />,
  ArrowNarrowUpOutlined: <ArrowNarrowUpOutlined />,
  ArrowRightOutlined: <ArrowRightOutlined />,
  ArrowSquareDownLeftOutlined: <ArrowSquareDownLeftOutlined />,
  ArrowSquareDownRightOutlined: <ArrowSquareDownRightOutlined />,
  ArrowSquareDownOutlined: <ArrowSquareDownOutlined />,
  ArrowSquareLeftOutlined: <ArrowSquareLeftOutlined />,
  ArrowSquareRightOutlined: <ArrowSquareRightOutlined />,
  ArrowSquareUpLeftOutlined: <ArrowSquareUpLeftOutlined />,
  ArrowSquareUpRightOutlined: <ArrowSquareUpRightOutlined />,
  ArrowSquareUpOutlined: <ArrowSquareUpOutlined />,
  ArrowUpLeftOutlined: <ArrowUpLeftOutlined />,
  ArrowUpRightOutlined: <ArrowUpRightOutlined />,
  ArrowUpOutlined: <ArrowUpOutlined />,
  ArrowsDownOutlined: <ArrowsDownOutlined />,
  ArrowsLeftOutlined: <ArrowsLeftOutlined />,
  ArrowsRightOutlined: <ArrowsRightOutlined />,
  ArrowsTriangleOutlined: <ArrowsTriangleOutlined />,
  ArrowsUpOutlined: <ArrowsUpOutlined />,
  Asterisk1Outlined: <Asterisk1Outlined />,
  Asterisk2Outlined: <Asterisk2Outlined />,
  AtSignOutlined: <AtSignOutlined />,
  Atom1Outlined: <Atom1Outlined />,
  Atom2Outlined: <Atom2Outlined />,
  Attachment1Outlined: <Attachment1Outlined />,
  Attachment2Outlined: <Attachment2Outlined />,
  Award1Outlined: <Award1Outlined />,
  Award2Outlined: <Award2Outlined />,
  Award3Outlined: <Award3Outlined />,
  Award4Outlined: <Award4Outlined />,
  Award5Outlined: <Award5Outlined />,
  BackpackOutlined: <BackpackOutlined />,
  BankNote1Outlined: <BankNote1Outlined />,
  BankNote2Outlined: <BankNote2Outlined />,
  BankNote3Outlined: <BankNote3Outlined />,
  Bank1Outlined: <Bank1Outlined />,
  Bank2Outlined: <Bank2Outlined />,
  Bank3Outlined: <Bank3Outlined />,
  BarChart1Outlined: <BarChart1Outlined />,
  BarChart2Outlined: <BarChart2Outlined />,
  BarChart3Outlined: <BarChart3Outlined />,
  BarChart4Outlined: <BarChart4Outlined />,
  BarChart5Outlined: <BarChart5Outlined />,
  BarChart6Outlined: <BarChart6Outlined />,
  BarChart7Outlined: <BarChart7Outlined />,
  BarChart8Outlined: <BarChart8Outlined />,
  BarChart9Outlined: <BarChart9Outlined />,
  BarChart10Outlined: <BarChart10Outlined />,
  BarChart11Outlined: <BarChart11Outlined />,
  BarChart12Outlined: <BarChart12Outlined />,
  BarChartCircle1Outlined: <BarChartCircle1Outlined />,
  BarChartCircle2Outlined: <BarChartCircle2Outlined />,
  BarChartCircle3Outlined: <BarChartCircle3Outlined />,
  BarChartSquare1Outlined: <BarChartSquare1Outlined />,
  BarChartSquare2Outlined: <BarChartSquare2Outlined />,
  BarChartSquare3Outlined: <BarChartSquare3Outlined />,
  BarChartSquareDownOutlined: <BarChartSquareDownOutlined />,
  BarChartSquareMinusOutlined: <BarChartSquareMinusOutlined />,
  BarChartSquarePlusOutlined: <BarChartSquarePlusOutlined />,
  BarChartSquareUpOutlined: <BarChartSquareUpOutlined />,
  BarLineChartOutlined: <BarLineChartOutlined />,
  BatteryCharging1Outlined: <BatteryCharging1Outlined />,
  BatteryCharging2Outlined: <BatteryCharging2Outlined />,
  BatteryEmptyOutlined: <BatteryEmptyOutlined />,
  BatteryFullOutlined: <BatteryFullOutlined />,
  BatteryLowOutlined: <BatteryLowOutlined />,
  BatteryMidOutlined: <BatteryMidOutlined />,
  Beaker1Outlined: <Beaker1Outlined />,
  Beaker2Outlined: <Beaker2Outlined />,
  Bell1Outlined: <Bell1Outlined />,
  Bell2Outlined: <Bell2Outlined />,
  Bell3Outlined: <Bell3Outlined />,
  Bell4Outlined: <Bell4Outlined />,
  BellMinusOutlined: <BellMinusOutlined />,
  BellOff1Outlined: <BellOff1Outlined />,
  BellOff2Outlined: <BellOff2Outlined />,
  BellOff3Outlined: <BellOff3Outlined />,
  BellPlusOutlined: <BellPlusOutlined />,
  BellRinging1Outlined: <BellRinging1Outlined />,
  BellRinging2Outlined: <BellRinging2Outlined />,
  BellRinging3Outlined: <BellRinging3Outlined />,
  BellRinging4Outlined: <BellRinging4Outlined />,
  BezierCurve1Outlined: <BezierCurve1Outlined />,
  BezierCurve2Outlined: <BezierCurve2Outlined />,
  BezierCurve3Outlined: <BezierCurve3Outlined />,
  BluetoothConnectOutlined: <BluetoothConnectOutlined />,
  BluetoothOnOutlined: <BluetoothOnOutlined />,
  BluetoothSignalOutlined: <BluetoothSignalOutlined />,
  BluetoothOutlined: <BluetoothOutlined />,
  Bold1Outlined: <Bold1Outlined />,
  Bold2Outlined: <Bold2Outlined />,
  BoldSquareOutlined: <BoldSquareOutlined />,
  BookClosedOutlined: <BookClosedOutlined />,
  BookOpen1Outlined: <BookOpen1Outlined />,
  BookOpen2Outlined: <BookOpen2Outlined />,
  BookmarkAddOutlined: <BookmarkAddOutlined />,
  BookmarkCheckOutlined: <BookmarkCheckOutlined />,
  BookmarkMinusOutlined: <BookmarkMinusOutlined />,
  BookmarkXOutlined: <BookmarkXOutlined />,
  BookmarkOutlined: <BookmarkOutlined />,
  BoxOutlined: <BoxOutlined />,
  BracketsCheckOutlined: <BracketsCheckOutlined />,
  BracketsEllipsesOutlined: <BracketsEllipsesOutlined />,
  BracketsMinusOutlined: <BracketsMinusOutlined />,
  BracketsPlusOutlined: <BracketsPlusOutlined />,
  BracketsSlashOutlined: <BracketsSlashOutlined />,
  BracketsXOutlined: <BracketsXOutlined />,
  BracketsOutlined: <BracketsOutlined />,
  Briefcase1Outlined: <Briefcase1Outlined />,
  Briefcase2Outlined: <Briefcase2Outlined />,
  BrowserOutlined: <BrowserOutlined />,
  Brush1Outlined: <Brush1Outlined />,
  Brush2Outlined: <Brush2Outlined />,
  Brush3Outlined: <Brush3Outlined />,
  Building1Outlined: <Building1Outlined />,
  Building2Outlined: <Building2Outlined />,
  Building3Outlined: <Building3Outlined />,
  Building4Outlined: <Building4Outlined />,
  Building5Outlined: <Building5Outlined />,
  Building6Outlined: <Building6Outlined />,
  BusOutlined: <BusOutlined />,
  CalculatorOutlined: <CalculatorOutlined />,
  CalendarCheck1Outlined: <CalendarCheck1Outlined />,
  CalendarCheck2Outlined: <CalendarCheck2Outlined />,
  CalendarDateOutlined: <CalendarDateOutlined />,
  CalendarHeart1Outlined: <CalendarHeart1Outlined />,
  CalendarHeart2Outlined: <CalendarHeart2Outlined />,
  CalendarMinus1Outlined: <CalendarMinus1Outlined />,
  CalendarMinus2Outlined: <CalendarMinus2Outlined />,
  CalendarPlus1Outlined: <CalendarPlus1Outlined />,
  CalendarPlus2Outlined: <CalendarPlus2Outlined />,
  CalendarOutlined: <CalendarOutlined />,
  Camera1Outlined: <Camera1Outlined />,
  Camera2Outlined: <Camera2Outlined />,
  Camera3Outlined: <Camera3Outlined />,
  CameraLensOutlined: <CameraLensOutlined />,
  CameraOffOutlined: <CameraOffOutlined />,
  CameraPlusOutlined: <CameraPlusOutlined />,
  CarOutlined: <CarOutlined />,
  Car1Outlined: <Car1Outlined />,
  Car2Outlined: <Car2Outlined />,
  Certificate1Outlined: <Certificate1Outlined />,
  Certificate2Outlined: <Certificate2Outlined />,
  ChartBreakoutCircleOutlined: <ChartBreakoutCircleOutlined />,
  ChartBreakoutSquareOutlined: <ChartBreakoutSquareOutlined />,
  CheckCircleBrokenOutlined: <CheckCircleBrokenOutlined />,
  CheckCircleOutlined: <CheckCircleOutlined />,
  CheckDone1Outlined: <CheckDone1Outlined />,
  CheckDone2Outlined: <CheckDone2Outlined />,
  CheckHeartOutlined: <CheckHeartOutlined />,
  CheckSquareBrokenOutlined: <CheckSquareBrokenOutlined />,
  CheckSquareOutlined: <CheckSquareOutlined />,
  CheckVerified1Outlined: <CheckVerified1Outlined />,
  CheckVerified2Outlined: <CheckVerified2Outlined />,
  CheckVerified3Outlined: <CheckVerified3Outlined />,
  CheckOutlined: <CheckOutlined />,
  ChevronDownDoubleOutlined: <ChevronDownDoubleOutlined />,
  ChevronDownOutlined: <ChevronDownOutlined />,
  ChevronLeftDoubleOutlined: <ChevronLeftDoubleOutlined />,
  ChevronLeftOutlined: <ChevronLeftOutlined />,
  ChevronRightDoubleOutlined: <ChevronRightDoubleOutlined />,
  ChevronRightOutlined: <ChevronRightOutlined />,
  ChevronSelectorHorizontalOutlined: <ChevronSelectorHorizontalOutlined />,
  ChevronSelectorVerticalOutlined: <ChevronSelectorVerticalOutlined />,
  ChevronUpDoubleOutlined: <ChevronUpDoubleOutlined />,
  ChevronUpOutlined: <ChevronUpOutlined />,
  ChromeCastOutlined: <ChromeCastOutlined />,
  CircleCutOutlined: <CircleCutOutlined />,
  CircleOutlined: <CircleOutlined />,
  ClapperboardOutlined: <ClapperboardOutlined />,
  ClipboardAttachmentOutlined: <ClipboardAttachmentOutlined />,
  ClipboardCheckOutlined: <ClipboardCheckOutlined />,
  ClipboardDownloadOutlined: <ClipboardDownloadOutlined />,
  ClipboardMinusOutlined: <ClipboardMinusOutlined />,
  ClipboardPlusOutlined: <ClipboardPlusOutlined />,
  ClipboardXOutlined: <ClipboardXOutlined />,
  ClipboardOutlined: <ClipboardOutlined />,
  ClockCheckOutlined: <ClockCheckOutlined />,
  ClockFastForwardOutlined: <ClockFastForwardOutlined />,
  ClockPlusOutlined: <ClockPlusOutlined />,
  ClockRefreshOutlined: <ClockRefreshOutlined />,
  ClockRewindOutlined: <ClockRewindOutlined />,
  ClockSnoozeOutlined: <ClockSnoozeOutlined />,
  ClockStopwatchOutlined: <ClockStopwatchOutlined />,
  ClockOutlined: <ClockOutlined />,
  Cloud1Outlined: <Cloud1Outlined />,
  Cloud2Outlined: <Cloud2Outlined />,
  Cloud3Outlined: <Cloud3Outlined />,
  CloudBlank1Outlined: <CloudBlank1Outlined />,
  CloudBlank2Outlined: <CloudBlank2Outlined />,
  CloudLightningOutlined: <CloudLightningOutlined />,
  CloudMoonOutlined: <CloudMoonOutlined />,
  CloudOffOutlined: <CloudOffOutlined />,
  CloudRaining1Outlined: <CloudRaining1Outlined />,
  CloudRaining2Outlined: <CloudRaining2Outlined />,
  CloudRaining3Outlined: <CloudRaining3Outlined />,
  CloudRaining4Outlined: <CloudRaining4Outlined />,
  CloudRaining5Outlined: <CloudRaining5Outlined />,
  CloudRaining6Outlined: <CloudRaining6Outlined />,
  CloudSnowing1Outlined: <CloudSnowing1Outlined />,
  CloudSnowing2Outlined: <CloudSnowing2Outlined />,
  CloudSun1Outlined: <CloudSun1Outlined />,
  CloudSun2Outlined: <CloudSun2Outlined />,
  CloudSun3Outlined: <CloudSun3Outlined />,
  Code1Outlined: <Code1Outlined />,
  Code2Outlined: <Code2Outlined />,
  CodeBrowserOutlined: <CodeBrowserOutlined />,
  CodeCircle1Outlined: <CodeCircle1Outlined />,
  CodeCircle2Outlined: <CodeCircle2Outlined />,
  CodeCircle3Outlined: <CodeCircle3Outlined />,
  CodeSnippet1Outlined: <CodeSnippet1Outlined />,
  CodeSnippet2Outlined: <CodeSnippet2Outlined />,
  CodeSquare1Outlined: <CodeSquare1Outlined />,
  CodeSquare2Outlined: <CodeSquare2Outlined />,
  CodepenOutlined: <CodepenOutlined />,
  Coins1Outlined: <Coins1Outlined />,
  Coins2Outlined: <Coins2Outlined />,
  Coins3Outlined: <Coins3Outlined />,
  Coins4Outlined: <Coins4Outlined />,
  CoinsHandOutlined: <CoinsHandOutlined />,
  CoinsStacked1Outlined: <CoinsStacked1Outlined />,
  CoinsStacked2Outlined: <CoinsStacked2Outlined />,
  CoinsStacked3Outlined: <CoinsStacked3Outlined />,
  CoinsStacked4Outlined: <CoinsStacked4Outlined />,
  CoinsSwap1Outlined: <CoinsSwap1Outlined />,
  CoinsSwap2Outlined: <CoinsSwap2Outlined />,
  Colors1Outlined: <Colors1Outlined />,
  ColorsOutlined: <ColorsOutlined />,
  Columns2Outlined: <Columns2Outlined />,
  Columns3Outlined: <Columns3Outlined />,
  CommandOutlined: <CommandOutlined />,
  Compass1Outlined: <Compass1Outlined />,
  Compass2Outlined: <Compass2Outlined />,
  Compass3Outlined: <Compass3Outlined />,
  CompassOutlined: <CompassOutlined />,
  ContainerOutlined: <ContainerOutlined />,
  Contrast1Outlined: <Contrast1Outlined />,
  Contrast2Outlined: <Contrast2Outlined />,
  Contrast3Outlined: <Contrast3Outlined />,
  Copy1Outlined: <Copy1Outlined />,
  Copy2Outlined: <Copy2Outlined />,
  Copy3Outlined: <Copy3Outlined />,
  Copy4Outlined: <Copy4Outlined />,
  Copy5Outlined: <Copy5Outlined />,
  Copy6Outlined: <Copy6Outlined />,
  Copy7Outlined: <Copy7Outlined />,
  CornerDownLeftOutlined: <CornerDownLeftOutlined />,
  CornerDownRightOutlined: <CornerDownRightOutlined />,
  CornerLeftDownOutlined: <CornerLeftDownOutlined />,
  CornerLeftUpOutlined: <CornerLeftUpOutlined />,
  CornerRightDownOutlined: <CornerRightDownOutlined />,
  CornerRightUpOutlined: <CornerRightUpOutlined />,
  CornerUpLeftOutlined: <CornerUpLeftOutlined />,
  CornerUpRightOutlined: <CornerUpRightOutlined />,
  CpuChip1Outlined: <CpuChip1Outlined />,
  CpuChip2Outlined: <CpuChip2Outlined />,
  CreditCard1Outlined: <CreditCard1Outlined />,
  CreditCard2Outlined: <CreditCard2Outlined />,
  CreditCardCheckOutlined: <CreditCardCheckOutlined />,
  CreditCardDownOutlined: <CreditCardDownOutlined />,
  CreditCardDownloadOutlined: <CreditCardDownloadOutlined />,
  CreditCardEditOutlined: <CreditCardEditOutlined />,
  CreditCardLockOutlined: <CreditCardLockOutlined />,
  CreditCardMinusOutlined: <CreditCardMinusOutlined />,
  CreditCardPlusOutlined: <CreditCardPlusOutlined />,
  CreditCardRefreshOutlined: <CreditCardRefreshOutlined />,
  CreditCardSearchOutlined: <CreditCardSearchOutlined />,
  CreditCardShieldOutlined: <CreditCardShieldOutlined />,
  CreditCardUpOutlined: <CreditCardUpOutlined />,
  CreditCardUploadOutlined: <CreditCardUploadOutlined />,
  CreditCardXOutlined: <CreditCardXOutlined />,
  Crop1Outlined: <Crop1Outlined />,
  Crop2Outlined: <Crop2Outlined />,
  Cryptocurrency1Outlined: <Cryptocurrency1Outlined />,
  Cryptocurrency2Outlined: <Cryptocurrency2Outlined />,
  Cryptocurrency3Outlined: <Cryptocurrency3Outlined />,
  Cryptocurrency4Outlined: <Cryptocurrency4Outlined />,
  Cube1Outlined: <Cube1Outlined />,
  Cube2Outlined: <Cube2Outlined />,
  Cube3Outlined: <Cube3Outlined />,
  Cube4Outlined: <Cube4Outlined />,
  CubeOutlineOutlined: <CubeOutlineOutlined />,
  CurrencyBitcoinCircleOutlined: <CurrencyBitcoinCircleOutlined />,
  CurrencyBitcoinOutlined: <CurrencyBitcoinOutlined />,
  CurrencyDollarCircleOutlined: <CurrencyDollarCircleOutlined />,
  CurrencyDollarOutlined: <CurrencyDollarOutlined />,
  CurrencyEthereumCircleOutlined: <CurrencyEthereumCircleOutlined />,
  CurrencyEthereumOutlined: <CurrencyEthereumOutlined />,
  CurrencyEuroCircleOutlined: <CurrencyEuroCircleOutlined />,
  CurrencyEuroOutlined: <CurrencyEuroOutlined />,
  CurrencyPoundCircleOutlined: <CurrencyPoundCircleOutlined />,
  CurrencyPoundOutlined: <CurrencyPoundOutlined />,
  CurrencyRubleCircleOutlined: <CurrencyRubleCircleOutlined />,
  CurrencyRubleOutlined: <CurrencyRubleOutlined />,
  CurrencyRupeeCircleOutlined: <CurrencyRupeeCircleOutlined />,
  CurrencyRupeeOutlined: <CurrencyRupeeOutlined />,
  CurrencyYenCircleOutlined: <CurrencyYenCircleOutlined />,
  CurrencyYenOutlined: <CurrencyYenOutlined />,
  Cursor1Outlined: <Cursor1Outlined />,
  Cursor2Outlined: <Cursor2Outlined />,
  Cursor3Outlined: <Cursor3Outlined />,
  Cursor4Outlined: <Cursor4Outlined />,
  CursorBoxOutlined: <CursorBoxOutlined />,
  CursorClick1Outlined: <CursorClick1Outlined />,
  CursorClick2Outlined: <CursorClick2Outlined />,
  Dashboard2Outlined: <Dashboard2Outlined />,
  DashboardOutlined: <DashboardOutlined />,
  DataOutlined: <DataOutlined />,
  Database1Outlined: <Database1Outlined />,
  Database2Outlined: <Database2Outlined />,
  Database3Outlined: <Database3Outlined />,
  Dataflow1Outlined: <Dataflow1Outlined />,
  Dataflow2Outlined: <Dataflow2Outlined />,
  Dataflow3Outlined: <Dataflow3Outlined />,
  Dataflow4Outlined: <Dataflow4Outlined />,
  DeleteOutlined: <DeleteOutlined />,
  Diamond1Outlined: <Diamond1Outlined />,
  Diamond2Outlined: <Diamond2Outlined />,
  Dice1Outlined: <Dice1Outlined />,
  Dice2Outlined: <Dice2Outlined />,
  Dice3Outlined: <Dice3Outlined />,
  Dice4Outlined: <Dice4Outlined />,
  Dice5Outlined: <Dice5Outlined />,
  Dice6Outlined: <Dice6Outlined />,
  Disc1Outlined: <Disc1Outlined />,
  Disc2Outlined: <Disc2Outlined />,
  DistributeSpacingHorizontalOutlined: <DistributeSpacingHorizontalOutlined />,
  DistributeSpacingVerticalOutlined: <DistributeSpacingVerticalOutlined />,
  Divide1Outlined: <Divide1Outlined />,
  Divide2Outlined: <Divide2Outlined />,
  Divide3Outlined: <Divide3Outlined />,
  DividerOutlined: <DividerOutlined />,
  Dotpoints1Outlined: <Dotpoints1Outlined />,
  Dotpoints2Outlined: <Dotpoints2Outlined />,
  DotsGridOutlined: <DotsGridOutlined />,
  DotsHorizontalOutlined: <DotsHorizontalOutlined />,
  DotsVerticalOutlined: <DotsVerticalOutlined />,
  Download1Outlined: <Download1Outlined />,
  Download2Outlined: <Download2Outlined />,
  Download3Outlined: <Download3Outlined />,
  Download4Outlined: <Download4Outlined />,
  DownloadCloud1Outlined: <DownloadCloud1Outlined />,
  DownloadCloud2Outlined: <DownloadCloud2Outlined />,
  DropOutlined: <DropOutlined />,
  Droplets1Outlined: <Droplets1Outlined />,
  Droplets2Outlined: <Droplets2Outlined />,
  Droplets3Outlined: <Droplets3Outlined />,
  DropperOutlined: <DropperOutlined />,
  DraggerOutlined: <DraggerOutlined />,
  Edit1Outlined: <Edit1Outlined />,
  Edit2Outlined: <Edit2Outlined />,
  Edit3Outlined: <Edit3Outlined />,
  Edit4Outlined: <Edit4Outlined />,
  Edit5Outlined: <Edit5Outlined />,
  EqualNotOutlined: <EqualNotOutlined />,
  EqualOutlined: <EqualOutlined />,
  EraserOutlined: <EraserOutlined />,
  Expand1Outlined: <Expand1Outlined />,
  Expand2Outlined: <Expand2Outlined />,
  Expand3Outlined: <Expand3Outlined />,
  Expand4Outlined: <Expand4Outlined />,
  Expand5Outlined: <Expand5Outlined />,
  Expand6Outlined: <Expand6Outlined />,
  EyeOffOutlined: <EyeOffOutlined />,
  EyeOutlined: <EyeOutlined />,
  FaceContentOutlined: <FaceContentOutlined />,
  FaceFrownOutlined: <FaceFrownOutlined />,
  FaceHappyOutlined: <FaceHappyOutlined />,
  FaceIdSquareOutlined: <FaceIdSquareOutlined />,
  FaceIdOutlined: <FaceIdOutlined />,
  FaceNeutralOutlined: <FaceNeutralOutlined />,
  FaceSadOutlined: <FaceSadOutlined />,
  FaceSmileOutlined: <FaceSmileOutlined />,
  FaceWinkOutlined: <FaceWinkOutlined />,
  FastBackwardOutlined: <FastBackwardOutlined />,
  FastForwardOutlined: <FastForwardOutlined />,
  FeatherOutlined: <FeatherOutlined />,
  FigmaOutlined: <FigmaOutlined />,
  File1Outlined: <File1Outlined />,
  File2Outlined: <File2Outlined />,
  File3Outlined: <File3Outlined />,
  File4Outlined: <File4Outlined />,
  File5Outlined: <File5Outlined />,
  File6Outlined: <File6Outlined />,
  File7Outlined: <File7Outlined />,
  FileAttachment1Outlined: <FileAttachment1Outlined />,
  FileAttachment2Outlined: <FileAttachment2Outlined />,
  FileAttachment3Outlined: <FileAttachment3Outlined />,
  FileAttachment4Outlined: <FileAttachment4Outlined />,
  FileAttachment5Outlined: <FileAttachment5Outlined />,
  FileCheck1Outlined: <FileCheck1Outlined />,
  FileCheck2Outlined: <FileCheck2Outlined />,
  FileCheck3Outlined: <FileCheck3Outlined />,
  FileCode1Outlined: <FileCode1Outlined />,
  FileCode2Outlined: <FileCode2Outlined />,
  FileDownload1Outlined: <FileDownload1Outlined />,
  FileDownload2Outlined: <FileDownload2Outlined />,
  FileDownload3Outlined: <FileDownload3Outlined />,
  FileHeart1Outlined: <FileHeart1Outlined />,
  FileHeart2Outlined: <FileHeart2Outlined />,
  FileHeart3Outlined: <FileHeart3Outlined />,
  FileLock1Outlined: <FileLock1Outlined />,
  FileLock2Outlined: <FileLock2Outlined />,
  FileLock3Outlined: <FileLock3Outlined />,
  FileMinus1Outlined: <FileMinus1Outlined />,
  FileMinus2Outlined: <FileMinus2Outlined />,
  FileMinus3Outlined: <FileMinus3Outlined />,
  FilePlus1Outlined: <FilePlus1Outlined />,
  FilePlus2Outlined: <FilePlus2Outlined />,
  FilePlus3Outlined: <FilePlus3Outlined />,
  FileQuestion1Outlined: <FileQuestion1Outlined />,
  FileQuestion2Outlined: <FileQuestion2Outlined />,
  FileQuestion3Outlined: <FileQuestion3Outlined />,
  FileSearch1Outlined: <FileSearch1Outlined />,
  FileSearch2Outlined: <FileSearch2Outlined />,
  FileSearch3Outlined: <FileSearch3Outlined />,
  FileShield1Outlined: <FileShield1Outlined />,
  FileShield2Outlined: <FileShield2Outlined />,
  FileShield3Outlined: <FileShield3Outlined />,
  FileUpload3Outlined: <FileUpload3Outlined />,
  FileX1Outlined: <FileX1Outlined />,
  FileX2Outlined: <FileX2Outlined />,
  FileX3Outlined: <FileX3Outlined />,
  Film1Outlined: <Film1Outlined />,
  Film2Outlined: <Film2Outlined />,
  Film3Outlined: <Film3Outlined />,
  FilterFunnel1Outlined: <FilterFunnel1Outlined />,
  FilterFunnel2Outlined: <FilterFunnel2Outlined />,
  FilterLinesOutlined: <FilterLinesOutlined />,
  Fingerprint1Outlined: <Fingerprint1Outlined />,
  Fingerprint2Outlined: <Fingerprint2Outlined />,
  Fingerprint3Outlined: <Fingerprint3Outlined />,
  Fingerprint4Outlined: <Fingerprint4Outlined />,
  Flag1Outlined: <Flag1Outlined />,
  Flag2Outlined: <Flag2Outlined />,
  Flag3Outlined: <Flag3Outlined />,
  Flag4Outlined: <Flag4Outlined />,
  Flag5Outlined: <Flag5Outlined />,
  Flag6Outlined: <Flag6Outlined />,
  FlashOffOutlined: <FlashOffOutlined />,
  FlashOutlined: <FlashOutlined />,
  FlexAlignBottomOutlined: <FlexAlignBottomOutlined />,
  FlexAlignLeftOutlined: <FlexAlignLeftOutlined />,
  FlexAlignRightOutlined: <FlexAlignRightOutlined />,
  FlexAlignTopOutlined: <FlexAlignTopOutlined />,
  FlipBackwardOutlined: <FlipBackwardOutlined />,
  FlipForwardOutlined: <FlipForwardOutlined />,
  FolderCheckOutlined: <FolderCheckOutlined />,
  FolderClosedOutlined: <FolderClosedOutlined />,
  FolderCodeOutlined: <FolderCodeOutlined />,
  FolderDownloadOutlined: <FolderDownloadOutlined />,
  FolderLockOutlined: <FolderLockOutlined />,
  FolderMinusOutlined: <FolderMinusOutlined />,
  FolderPlusOutlined: <FolderPlusOutlined />,
  FolderQuestionOutlined: <FolderQuestionOutlined />,
  FolderSearchOutlined: <FolderSearchOutlined />,
  FolderShieldOutlined: <FolderShieldOutlined />,
  FolderXOutlined: <FolderXOutlined />,
  FolderOutlined: <FolderOutlined />,
  FramerOutlined: <FramerOutlined />,
  FuelStationOutlined: <FuelStationOutlined />,
  GamingPad1Outlined: <GamingPad1Outlined />,
  GamingPad2Outlined: <GamingPad2Outlined />,
  Gift1Outlined: <Gift1Outlined />,
  Gift2Outlined: <Gift2Outlined />,
  GitBranch1Outlined: <GitBranch1Outlined />,
  GitBranch2Outlined: <GitBranch2Outlined />,
  GitCommitOutlined: <GitCommitOutlined />,
  GitMergeOutlined: <GitMergeOutlined />,
  GitPullRequestOutlined: <GitPullRequestOutlined />,
  Glasses1Outlined: <Glasses1Outlined />,
  Glasses2Outlined: <Glasses2Outlined />,
  Globe11Outlined: <Globe11Outlined />,
  Globe1Outlined: <Globe1Outlined />,
  Globe21Outlined: <Globe21Outlined />,
  Globe2Outlined: <Globe2Outlined />,
  Globe3Outlined: <Globe3Outlined />,
  Globe4Outlined: <Globe4Outlined />,
  Globe5Outlined: <Globe5Outlined />,
  Globe6Outlined: <Globe6Outlined />,
  GoogleChromeOutlined: <GoogleChromeOutlined />,
  GraduationHat1Outlined: <GraduationHat1Outlined />,
  GraduationHat2Outlined: <GraduationHat2Outlined />,
  Grid1Outlined: <Grid1Outlined />,
  Grid2Outlined: <Grid2Outlined />,
  Grid3Outlined: <Grid3Outlined />,
  GridDotsBlankOutlined: <GridDotsBlankOutlined />,
  GridDotsBottomOutlined: <GridDotsBottomOutlined />,
  GridDotsHorizontalCenterOutlined: <GridDotsHorizontalCenterOutlined />,
  GridDotsLeftOutlined: <GridDotsLeftOutlined />,
  GridDotsOuterOutlined: <GridDotsOuterOutlined />,
  GridDotsRightOutlined: <GridDotsRightOutlined />,
  GridDotsTopOutlined: <GridDotsTopOutlined />,
  GridDotsVerticalCenterOutlined: <GridDotsVerticalCenterOutlined />,
  GridOutlined: <GridOutlined />,
  HandOutlined: <HandOutlined />,
  HardDriveOutlined: <HardDriveOutlined />,
  Hash1Outlined: <Hash1Outlined />,
  Hash2Outlined: <Hash2Outlined />,
  Heading1Outlined: <Heading1Outlined />,
  Heading2Outlined: <Heading2Outlined />,
  HeadingSquareOutlined: <HeadingSquareOutlined />,
  Headphones1Outlined: <Headphones1Outlined />,
  Headphones2Outlined: <Headphones2Outlined />,
  HeartCircleOutlined: <HeartCircleOutlined />,
  HeartHandOutlined: <HeartHandOutlined />,
  HeartOctagonOutlined: <HeartOctagonOutlined />,
  HeartRoundedOutlined: <HeartRoundedOutlined />,
  HeartSquareOutlined: <HeartSquareOutlined />,
  HeartOutlined: <HeartOutlined />,
  HeartsOutlined: <HeartsOutlined />,
  HelpCircleOutlined: <HelpCircleOutlined />,
  HelpHexagonOutlined: <HelpHexagonOutlined />,
  HelpOctagon1Outlined: <HelpOctagon1Outlined />,
  HelpOctagonOutlined: <HelpOctagonOutlined />,
  HelpSquareOutlined: <HelpSquareOutlined />,
  Hexagon1Outlined: <Hexagon1Outlined />,
  Hexagon2Outlined: <Hexagon2Outlined />,
  Home1Outlined: <Home1Outlined />,
  Home2Outlined: <Home2Outlined />,
  Home3Outlined: <Home3Outlined />,
  Home4Outlined: <Home4Outlined />,
  Home5Outlined: <Home5Outlined />,
  HomeLineOutlined: <HomeLineOutlined />,
  HomeSmileOutlined: <HomeSmileOutlined />,
  HorizontalBarChart1Outlined: <HorizontalBarChart1Outlined />,
  HorizontalBarChart2Outlined: <HorizontalBarChart2Outlined />,
  HorizontalBarChart3Outlined: <HorizontalBarChart3Outlined />,
  Hourglass1Outlined: <Hourglass1Outlined />,
  Hourglass2Outlined: <Hourglass2Outlined />,
  Hourglass3Outlined: <Hourglass3Outlined />,
  Hurricane1Outlined: <Hurricane1Outlined />,
  Hurricane2Outlined: <Hurricane2Outlined />,
  Hurricane3Outlined: <Hurricane3Outlined />,
  Image1Outlined: <Image1Outlined />,
  Image2Outlined: <Image2Outlined />,
  Image3Outlined: <Image3Outlined />,
  Image4Outlined: <Image4Outlined />,
  Image5Outlined: <Image5Outlined />,
  ImageCheckOutlined: <ImageCheckOutlined />,
  ImageDownOutlined: <ImageDownOutlined />,
  ImageIndentLeftOutlined: <ImageIndentLeftOutlined />,
  ImageIndentRightOutlined: <ImageIndentRightOutlined />,
  ImageLeftOutlined: <ImageLeftOutlined />,
  ImagePlusOutlined: <ImagePlusOutlined />,
  ImageRightOutlined: <ImageRightOutlined />,
  ImageUpOutlined: <ImageUpOutlined />,
  ImageUserCheckOutlined: <ImageUserCheckOutlined />,
  ImageUserDownOutlined: <ImageUserDownOutlined />,
  ImageUserLeftOutlined: <ImageUserLeftOutlined />,
  ImageUserPlusOutlined: <ImageUserPlusOutlined />,
  ImageUserRightOutlined: <ImageUserRightOutlined />,
  ImageUserUpOutlined: <ImageUserUpOutlined />,
  ImageUserXOutlined: <ImageUserXOutlined />,
  ImageUserOutlined: <ImageUserOutlined />,
  ImageXOutlined: <ImageXOutlined />,
  Inbox1Outlined: <Inbox1Outlined />,
  Inbox2Outlined: <Inbox2Outlined />,
  InfinityOutlined: <InfinityOutlined />,
  InfoCircleOutlined: <InfoCircleOutlined />,
  InfoHexagonOutlined: <InfoHexagonOutlined />,
  InfoOctagonOutlined: <InfoOctagonOutlined />,
  InfoSquareOutlined: <InfoSquareOutlined />,
  IntersectCircleOutlined: <IntersectCircleOutlined />,
  IntersectSquareOutlined: <IntersectSquareOutlined />,
  Italic1Outlined: <Italic1Outlined />,
  Italic2Outlined: <Italic2Outlined />,
  ItalicSquareOutlined: <ItalicSquareOutlined />,
  Key1Outlined: <Key1Outlined />,
  Key2Outlined: <Key2Outlined />,
  Keyboard1Outlined: <Keyboard1Outlined />,
  Keyboard2Outlined: <Keyboard2Outlined />,
  Laptop1Outlined: <Laptop1Outlined />,
  Laptop2Outlined: <Laptop2Outlined />,
  LayerSingleOutlined: <LayerSingleOutlined />,
  LayersThree1Outlined: <LayersThree1Outlined />,
  LayersThree2Outlined: <LayersThree2Outlined />,
  LayersTwo1Outlined: <LayersTwo1Outlined />,
  LayersTwo2Outlined: <LayersTwo2Outlined />,
  LayoutAlt1Outlined: <LayoutAlt1Outlined />,
  LayoutAlt2Outlined: <LayoutAlt2Outlined />,
  LayoutAlt3Outlined: <LayoutAlt3Outlined />,
  LayoutAlt4Outlined: <LayoutAlt4Outlined />,
  LayoutBottomOutlined: <LayoutBottomOutlined />,
  LayoutGrid1Outlined: <LayoutGrid1Outlined />,
  LayoutGrid2Outlined: <LayoutGrid2Outlined />,
  LayoutLeftOutlined: <LayoutLeftOutlined />,
  LayoutRightOutlined: <LayoutRightOutlined />,
  LayoutTopOutlined: <LayoutTopOutlined />,
  LeftIndent1Outlined: <LeftIndent1Outlined />,
  LeftIndent2Outlined: <LeftIndent2Outlined />,
  LetterSpacing1Outlined: <LetterSpacing1Outlined />,
  LetterSpacing2Outlined: <LetterSpacing2Outlined />,
  LifeBuoy1Outlined: <LifeBuoy1Outlined />,
  LifeBuoy2Outlined: <LifeBuoy2Outlined />,
  Lightbulb1Outlined: <Lightbulb1Outlined />,
  Lightbulb2Outlined: <Lightbulb2Outlined />,
  Lightbulb3Outlined: <Lightbulb3Outlined />,
  Lightbulb4Outlined: <Lightbulb4Outlined />,
  Lightbulb5Outlined: <Lightbulb5Outlined />,
  Lightning1Outlined: <Lightning1Outlined />,
  Lightning2Outlined: <Lightning2Outlined />,
  LineChartDown1Outlined: <LineChartDown1Outlined />,
  LineChartDown2Outlined: <LineChartDown2Outlined />,
  LineChartDown3Outlined: <LineChartDown3Outlined />,
  LineChartDown4Outlined: <LineChartDown4Outlined />,
  LineChartDown5Outlined: <LineChartDown5Outlined />,
  LineChartUp1Outlined: <LineChartUp1Outlined />,
  LineChartUp2Outlined: <LineChartUp2Outlined />,
  LineChartUp3Outlined: <LineChartUp3Outlined />,
  LineChartUp4Outlined: <LineChartUp4Outlined />,
  LineChartUp5Outlined: <LineChartUp5Outlined />,
  LineHeightOutlined: <LineHeightOutlined />,
  Link1Outlined: <Link1Outlined />,
  Link2Outlined: <Link2Outlined />,
  Link3Outlined: <Link3Outlined />,
  Link4Outlined: <Link4Outlined />,
  Link5Outlined: <Link5Outlined />,
  LinkBroken1Outlined: <LinkBroken1Outlined />,
  LinkBroken2Outlined: <LinkBroken2Outlined />,
  LinkExternal1Outlined: <LinkExternal1Outlined />,
  LinkExternal2Outlined: <LinkExternal2Outlined />,
  ListOutlined: <ListOutlined />,
  Loading1Outlined: <Loading1Outlined />,
  Loading2Outlined: <Loading2Outlined />,
  Loading3Outlined: <Loading3Outlined />,
  Lock1Outlined: <Lock1Outlined />,
  Lock2Outlined: <Lock2Outlined />,
  Lock3Outlined: <Lock3Outlined />,
  Lock4Outlined: <Lock4Outlined />,
  LockKeyholeCircleOutlined: <LockKeyholeCircleOutlined />,
  LockKeyholeSquareOutlined: <LockKeyholeSquareOutlined />,
  LockUnlocked1Outlined: <LockUnlocked1Outlined />,
  LockUnlocked2Outlined: <LockUnlocked2Outlined />,
  LockUnlocked3Outlined: <LockUnlocked3Outlined />,
  LockUnlocked4Outlined: <LockUnlocked4Outlined />,
  LogIn1Outlined: <LogIn1Outlined />,
  LogIn2Outlined: <LogIn2Outlined />,
  LogIn3Outlined: <LogIn3Outlined />,
  LogIn4Outlined: <LogIn4Outlined />,
  LogOut1Outlined: <LogOut1Outlined />,
  LogOut2Outlined: <LogOut2Outlined />,
  LogOut3Outlined: <LogOut3Outlined />,
  LogOut4Outlined: <LogOut4Outlined />,
  Luggage1Outlined: <Luggage1Outlined />,
  Luggage2Outlined: <Luggage2Outlined />,
  Luggage3Outlined: <Luggage3Outlined />,
  MagicWand1Outlined: <MagicWand1Outlined />,
  MagicWand2Outlined: <MagicWand2Outlined />,
  Mail1Outlined: <Mail1Outlined />,
  Mail2Outlined: <Mail2Outlined />,
  Mail3Outlined: <Mail3Outlined />,
  Mail4Outlined: <Mail4Outlined />,
  Mail5Outlined: <Mail5Outlined />,
  Map1Outlined: <Map1Outlined />,
  Map2Outlined: <Map2Outlined />,
  MarkOutlined: <MarkOutlined />,
  MarkerPin1Outlined: <MarkerPin1Outlined />,
  MarkerPin2Outlined: <MarkerPin2Outlined />,
  MarkerPin3Outlined: <MarkerPin3Outlined />,
  MarkerPin4Outlined: <MarkerPin4Outlined />,
  MarkerPin5Outlined: <MarkerPin5Outlined />,
  MarkerPin6Outlined: <MarkerPin6Outlined />,
  Maximize1Outlined: <Maximize1Outlined />,
  Maximize2Outlined: <Maximize2Outlined />,
  MedicalCircleOutlined: <MedicalCircleOutlined />,
  MedicalCrossOutlined: <MedicalCrossOutlined />,
  MedicalSquareOutlined: <MedicalSquareOutlined />,
  Menu1Outlined: <Menu1Outlined />,
  Menu2Outlined: <Menu2Outlined />,
  Menu3Outlined: <Menu3Outlined />,
  Menu4Outlined: <Menu4Outlined />,
  Menu5Outlined: <Menu5Outlined />,
  MessageAlertCircleOutlined: <MessageAlertCircleOutlined />,
  MessageAlertSquareOutlined: <MessageAlertSquareOutlined />,
  MessageChatCircleOutlined: <MessageChatCircleOutlined />,
  MessageChatSquareOutlined: <MessageChatSquareOutlined />,
  MessageCheckCircleOutlined: <MessageCheckCircleOutlined />,
  MessageCheckSquareOutlined: <MessageCheckSquareOutlined />,
  MessageCircle1Outlined: <MessageCircle1Outlined />,
  MessageCircle2Outlined: <MessageCircle2Outlined />,
  MessageDotsCircleOutlined: <MessageDotsCircleOutlined />,
  MessageDotsSquareOutlined: <MessageDotsSquareOutlined />,
  MessageHeartCircleOutlined: <MessageHeartCircleOutlined />,
  MessageHeartSquareOutlined: <MessageHeartSquareOutlined />,
  MessageNotificationCircleOutlined: <MessageNotificationCircleOutlined />,
  MessageNotificationSquare1Outlined: <MessageNotificationSquare1Outlined />,
  MessageNotificationSquareOutlined: <MessageNotificationSquareOutlined />,
  MessagePlusCircleOutlined: <MessagePlusCircleOutlined />,
  MessagePlusSquareOutlined: <MessagePlusSquareOutlined />,
  MessageQuestionCircleOutlined: <MessageQuestionCircleOutlined />,
  MessageQuestionSquareOutlined: <MessageQuestionSquareOutlined />,
  MessageSmileCircleOutlined: <MessageSmileCircleOutlined />,
  MessageSmileSquareOutlined: <MessageSmileSquareOutlined />,
  MessageSquare1Outlined: <MessageSquare1Outlined />,
  MessageSquare2Outlined: <MessageSquare2Outlined />,
  MessageTextCircle1Outlined: <MessageTextCircle1Outlined />,
  MessageTextCircle2Outlined: <MessageTextCircle2Outlined />,
  MessageTextSquare1Outlined: <MessageTextSquare1Outlined />,
  MessageTextSquare2Outlined: <MessageTextSquare2Outlined />,
  MessageXCircleOutlined: <MessageXCircleOutlined />,
  MessageXSquareOutlined: <MessageXSquareOutlined />,
  Microphone1Outlined: <Microphone1Outlined />,
  Microphone2Outlined: <Microphone2Outlined />,
  MicrophoneOff1Outlined: <MicrophoneOff1Outlined />,
  MicrophoneOff2Outlined: <MicrophoneOff2Outlined />,
  MicroscopeOutlined: <MicroscopeOutlined />,
  Minimize1Outlined: <Minimize1Outlined />,
  Minimize2Outlined: <Minimize2Outlined />,
  MinusCircleOutlined: <MinusCircleOutlined />,
  MinusSquareOutlined: <MinusSquareOutlined />,
  MinusOutlined: <MinusOutlined />,
  Modem1Outlined: <Modem1Outlined />,
  Modem2Outlined: <Modem2Outlined />,
  Monitor1Outlined: <Monitor1Outlined />,
  Monitor2Outlined: <Monitor2Outlined />,
  Monitor3Outlined: <Monitor3Outlined />,
  Monitor4Outlined: <Monitor4Outlined />,
  Monitor5Outlined: <Monitor5Outlined />,
  Moon1Outlined: <Moon1Outlined />,
  Moon2Outlined: <Moon2Outlined />,
  MoonEclipseOutlined: <MoonEclipseOutlined />,
  MoonStarOutlined: <MoonStarOutlined />,
  MouseOutlined: <MouseOutlined />,
  MoveOutlined: <MoveOutlined />,
  MopedOutlined: <MopedOutlined />,
  MusicNote1Outlined: <MusicNote1Outlined />,
  MusicNote2Outlined: <MusicNote2Outlined />,
  MusicOutlined: <MusicOutlined />,
  NavigationPointer1Outlined: <NavigationPointer1Outlined />,
  NavigationPointer2Outlined: <NavigationPointer2Outlined />,
  NavigationPointerOff1Outlined: <NavigationPointerOff1Outlined />,
  NavigationPointerOff2Outlined: <NavigationPointerOff2Outlined />,
  NotificationBoxOutlined: <NotificationBoxOutlined />,
  NotificationTextOutlined: <NotificationTextOutlined />,
  OctagonOutlined: <OctagonOutlined />,
  PackageCheckOutlined: <PackageCheckOutlined />,
  PackageMinusOutlined: <PackageMinusOutlined />,
  PackagePlusOutlined: <PackagePlusOutlined />,
  PackageSearchOutlined: <PackageSearchOutlined />,
  PackageXOutlined: <PackageXOutlined />,
  PackageOutlined: <PackageOutlined />,
  PaintPourOutlined: <PaintPourOutlined />,
  PaintOutlined: <PaintOutlined />,
  PaletteOutlined: <PaletteOutlined />,
  PaperclipOutlined: <PaperclipOutlined />,
  ParagraphSpacingOutlined: <ParagraphSpacingOutlined />,
  ParagraphWrapOutlined: <ParagraphWrapOutlined />,
  ParkingOutlined: <ParkingOutlined />,
  PasscodeLockOutlined: <PasscodeLockOutlined />,
  PasscodeOutlined: <PasscodeOutlined />,
  PassportOutlined: <PassportOutlined />,
  PauseCircleOutlined: <PauseCircleOutlined />,
  PauseSquareOutlined: <PauseSquareOutlined />,
  PenTool1Outlined: <PenTool1Outlined />,
  PenTool2Outlined: <PenTool2Outlined />,
  PenToolMinusOutlined: <PenToolMinusOutlined />,
  PenToolPlusOutlined: <PenToolPlusOutlined />,
  Pencil1Outlined: <Pencil1Outlined />,
  Pencil2Outlined: <Pencil2Outlined />,
  PencilLineOutlined: <PencilLineOutlined />,
  PentagonOutlined: <PentagonOutlined />,
  Percent1Outlined: <Percent1Outlined />,
  Percent2Outlined: <Percent2Outlined />,
  Percent3Outlined: <Percent3Outlined />,
  Perspective1Outlined: <Perspective1Outlined />,
  Perspective2Outlined: <Perspective2Outlined />,
  Phone1Outlined: <Phone1Outlined />,
  Phone2Outlined: <Phone2Outlined />,
  PhoneCall1Outlined: <PhoneCall1Outlined />,
  PhoneCall2Outlined: <PhoneCall2Outlined />,
  PhoneHangUpOutlined: <PhoneHangUpOutlined />,
  PhoneIncoming1Outlined: <PhoneIncoming1Outlined />,
  PhoneIncoming2Outlined: <PhoneIncoming2Outlined />,
  PhoneOutgoing1Outlined: <PhoneOutgoing1Outlined />,
  PhoneOutgoing2Outlined: <PhoneOutgoing2Outlined />,
  PhonePauseOutlined: <PhonePauseOutlined />,
  PhonePlusOutlined: <PhonePlusOutlined />,
  PhoneXOutlined: <PhoneXOutlined />,
  PhoneOutlined: <PhoneOutlined />,
  PieChart1Outlined: <PieChart1Outlined />,
  PieChart2Outlined: <PieChart2Outlined />,
  PieChart3Outlined: <PieChart3Outlined />,
  PieChart4Outlined: <PieChart4Outlined />,
  PiggyBank1Outlined: <PiggyBank1Outlined />,
  PiggyBank2Outlined: <PiggyBank2Outlined />,
  Pilcrow1Outlined: <Pilcrow1Outlined />,
  Pilcrow2Outlined: <Pilcrow2Outlined />,
  PilcrowSquareOutlined: <PilcrowSquareOutlined />,
  Pin1Outlined: <Pin1Outlined />,
  Pin2Outlined: <Pin2Outlined />,
  PlaceholderOutlined: <PlaceholderOutlined />,
  PlayCircleOutlined: <PlayCircleOutlined />,
  PlaySquareOutlined: <PlaySquareOutlined />,
  PlayOutlined: <PlayOutlined />,
  PlugStationOutlined: <PlugStationOutlined />,
  PlusCircleOutlined: <PlusCircleOutlined />,
  PlusSquareOutlined: <PlusSquareOutlined />,
  PlusOutlined: <PlusOutlined />,
  PodcastOutlined: <PodcastOutlined />,
  Power1Outlined: <Power1Outlined />,
  Power2Outlined: <Power2Outlined />,
  Power3Outlined: <Power3Outlined />,
  PresentationChart1Outlined: <PresentationChart1Outlined />,
  PresentationChart2Outlined: <PresentationChart2Outlined />,
  PresentationChart3Outlined: <PresentationChart3Outlined />,
  PrinterOutlined: <PrinterOutlined />,
  PuzzlePiece2Outlined: <PuzzlePiece2Outlined />,
  PuzzlePieceOutlined: <PuzzlePieceOutlined />,
  QrCode1Outlined: <QrCode1Outlined />,
  QrCode2Outlined: <QrCode2Outlined />,
  ReceiptCheckOutlined: <ReceiptCheckOutlined />,
  ReceiptOutlined: <ReceiptOutlined />,
  Recording1Outlined: <Recording1Outlined />,
  Recording2Outlined: <Recording2Outlined />,
  Recording3Outlined: <Recording3Outlined />,
  Reflect1Outlined: <Reflect1Outlined />,
  Reflect2Outlined: <Reflect2Outlined />,
  RefreshCcw1Outlined: <RefreshCcw1Outlined />,
  RefreshCcw2Outlined: <RefreshCcw2Outlined />,
  RefreshCcw3Outlined: <RefreshCcw3Outlined />,
  RefreshCcw4Outlined: <RefreshCcw4Outlined />,
  RefreshCcw5Outlined: <RefreshCcw5Outlined />,
  RefreshCw1Outlined: <RefreshCw1Outlined />,
  RefreshCw2Outlined: <RefreshCw2Outlined />,
  RefreshCw3Outlined: <RefreshCw3Outlined />,
  RefreshCw4Outlined: <RefreshCw4Outlined />,
  RefreshCw5Outlined: <RefreshCw5Outlined />,
  Repeat1Outlined: <Repeat1Outlined />,
  Repeat2Outlined: <Repeat2Outlined />,
  Repeat3Outlined: <Repeat3Outlined />,
  Repeat4Outlined: <Repeat4Outlined />,
  ReverseLeftOutlined: <ReverseLeftOutlined />,
  ReverseRightOutlined: <ReverseRightOutlined />,
  RightIndent1Outlined: <RightIndent1Outlined />,
  RightIndent2Outlined: <RightIndent2Outlined />,
  Rocket1Outlined: <Rocket1Outlined />,
  Rocket2Outlined: <Rocket2Outlined />,
  RollerBrushOutlined: <RollerBrushOutlined />,
  RouteOutlined: <RouteOutlined />,
  Rows1Outlined: <Rows1Outlined />,
  Rows2Outlined: <Rows2Outlined />,
  Rows3Outlined: <Rows3Outlined />,
  Rss1Outlined: <Rss1Outlined />,
  Rss2Outlined: <Rss2Outlined />,
  RulerOutlined: <RulerOutlined />,
  SafeOutlined: <SafeOutlined />,
  Sale1Outlined: <Sale1Outlined />,
  Sale2Outlined: <Sale2Outlined />,
  Sale3Outlined: <Sale3Outlined />,
  Sale4Outlined: <Sale4Outlined />,
  Save1Outlined: <Save1Outlined />,
  Save2Outlined: <Save2Outlined />,
  Save3Outlined: <Save3Outlined />,
  Scale1Outlined: <Scale1Outlined />,
  Scale2Outlined: <Scale2Outlined />,
  Scale3Outlined: <Scale3Outlined />,
  Scales1Outlined: <Scales1Outlined />,
  Scales2Outlined: <Scales2Outlined />,
  ScanOutlined: <ScanOutlined />,
  Scissors1Outlined: <Scissors1Outlined />,
  Scissors2Outlined: <Scissors2Outlined />,
  ScissorsCut1Outlined: <ScissorsCut1Outlined />,
  ScissorsCut2Outlined: <ScissorsCut2Outlined />,
  SearchLgOutlined: <SearchLgOutlined />,
  SearchMdOutlined: <SearchMdOutlined />,
  SearchRefractionOutlined: <SearchRefractionOutlined />,
  SearchSmOutlined: <SearchSmOutlined />,
  Send1Outlined: <Send1Outlined />,
  Send2Outlined: <Send2Outlined />,
  Send3Outlined: <Send3Outlined />,
  Server1Outlined: <Server1Outlined />,
  Server2Outlined: <Server2Outlined />,
  Server3Outlined: <Server3Outlined />,
  Server4Outlined: <Server4Outlined />,
  Server5Outlined: <Server5Outlined />,
  Server6Outlined: <Server6Outlined />,
  Settings1Outlined: <Settings1Outlined />,
  Settings2Outlined: <Settings2Outlined />,
  Settings3Outlined: <Settings3Outlined />,
  Settings4Outlined: <Settings4Outlined />,
  Share1Outlined: <Share1Outlined />,
  Share2Outlined: <Share2Outlined />,
  Share3Outlined: <Share3Outlined />,
  Share4Outlined: <Share4Outlined />,
  Share5Outlined: <Share5Outlined />,
  Share6Outlined: <Share6Outlined />,
  Share7Outlined: <Share7Outlined />,
  Shield1Outlined: <Shield1Outlined />,
  Shield2Outlined: <Shield2Outlined />,
  Shield3Outlined: <Shield3Outlined />,
  ShieldDollarOutlined: <ShieldDollarOutlined />,
  ShieldOffOutlined: <ShieldOffOutlined />,
  ShieldPlusOutlined: <ShieldPlusOutlined />,
  ShieldTickOutlined: <ShieldTickOutlined />,
  ShieldZapOutlined: <ShieldZapOutlined />,
  ShipOutlined: <ShipOutlined />,
  ShoppingBag1Outlined: <ShoppingBag1Outlined />,
  ShoppingBag2Outlined: <ShoppingBag2Outlined />,
  ShoppingBag3Outlined: <ShoppingBag3Outlined />,
  ShoppingCart1Outlined: <ShoppingCart1Outlined />,
  ShoppingCart2Outlined: <ShoppingCart2Outlined />,
  ShoppingCart3Outlined: <ShoppingCart3Outlined />,
  Shuffle1Outlined: <Shuffle1Outlined />,
  Shuffle2Outlined: <Shuffle2Outlined />,
  Signal1OffOutlined: <Signal1OffOutlined />,
  Signal1Outlined: <Signal1Outlined />,
  Signal2OffOutlined: <Signal2OffOutlined />,
  Signal2Outlined: <Signal2Outlined />,
  Signal3Outlined: <Signal3Outlined />,
  SimcardOutlined: <SimcardOutlined />,
  SkewOutlined: <SkewOutlined />,
  SkipBackOutlined: <SkipBackOutlined />,
  SkipForwardOutlined: <SkipForwardOutlined />,
  SlashCircle1Outlined: <SlashCircle1Outlined />,
  SlashCircle2Outlined: <SlashCircle2Outlined />,
  SlashDividerOutlined: <SlashDividerOutlined />,
  SlashOctagonOutlined: <SlashOctagonOutlined />,
  Sliders1Outlined: <Sliders1Outlined />,
  Sliders2Outlined: <Sliders2Outlined />,
  Sliders3Outlined: <Sliders3Outlined />,
  Sliders4Outlined: <Sliders4Outlined />,
  Snowflake1Outlined: <Snowflake1Outlined />,
  Snowflake2Outlined: <Snowflake2Outlined />,
  SpacingHeight1Outlined: <SpacingHeight1Outlined />,
  SpacingHeight2Outlined: <SpacingHeight2Outlined />,
  SpacingWidth1Outlined: <SpacingWidth1Outlined />,
  SpacingWidth2Outlined: <SpacingWidth2Outlined />,
  Speaker1Outlined: <Speaker1Outlined />,
  Speaker2Outlined: <Speaker2Outlined />,
  Speaker3Outlined: <Speaker3Outlined />,
  Speedometer1Outlined: <Speedometer1Outlined />,
  Speedometer2Outlined: <Speedometer2Outlined />,
  Speedometer3Outlined: <Speedometer3Outlined />,
  Speedometer4Outlined: <Speedometer4Outlined />,
  SquareOutlined: <SquareOutlined />,
  StandOutlined: <StandOutlined />,
  Star1Outlined: <Star1Outlined />,
  Star2Outlined: <Star2Outlined />,
  Star3Outlined: <Star3Outlined />,
  Star4Outlined: <Star4Outlined />,
  Star5Outlined: <Star5Outlined />,
  Star6Outlined: <Star6Outlined />,
  Star7Outlined: <Star7Outlined />,
  Stars1Outlined: <Stars1Outlined />,
  Stars2Outlined: <Stars2Outlined />,
  Stars3Outlined: <Stars3Outlined />,
  StickerCircleOutlined: <StickerCircleOutlined />,
  StickerSquareOutlined: <StickerSquareOutlined />,
  StopCircleOutlined: <StopCircleOutlined />,
  StopSquareOutlined: <StopSquareOutlined />,
  StopOutlined: <StopOutlined />,
  StoreOutlined: <StoreOutlined />,
  Strikethrough1Outlined: <Strikethrough1Outlined />,
  Strikethrough2Outlined: <Strikethrough2Outlined />,
  StrikethroughSquareOutlined: <StrikethroughSquareOutlined />,
  SubscriptOutlined: <SubscriptOutlined />,
  SunSetting1Outlined: <SunSetting1Outlined />,
  SunSetting2Outlined: <SunSetting2Outlined />,
  SunSetting3Outlined: <SunSetting3Outlined />,
  SunOutlined: <SunOutlined />,
  SunriseOutlined: <SunriseOutlined />,
  SunsetOutlined: <SunsetOutlined />,
  SwitchHorizontal1Outlined: <SwitchHorizontal1Outlined />,
  SwitchHorizontal2Outlined: <SwitchHorizontal2Outlined />,
  SwitchVertical1Outlined: <SwitchVertical1Outlined />,
  SwitchVertical2Outlined: <SwitchVertical2Outlined />,
  TableOutlined: <TableOutlined />,
  Tablet1Outlined: <Tablet1Outlined />,
  Tablet2Outlined: <Tablet2Outlined />,
  Tag1Outlined: <Tag1Outlined />,
  Tag2Outlined: <Tag2Outlined />,
  Tag3Outlined: <Tag3Outlined />,
  Target1Outlined: <Target1Outlined />,
  Target2Outlined: <Target2Outlined />,
  Target3Outlined: <Target3Outlined />,
  Target4Outlined: <Target4Outlined />,
  Target5Outlined: <Target5Outlined />,
  TelescopeOutlined: <TelescopeOutlined />,
  TerminalBrowserOutlined: <TerminalBrowserOutlined />,
  TerminalCircleOutlined: <TerminalCircleOutlined />,
  TerminalSquareOutlined: <TerminalSquareOutlined />,
  TerminalOutlined: <TerminalOutlined />,
  TextInputOutlined: <TextInputOutlined />,
  Thermometer1Outlined: <Thermometer1Outlined />,
  Thermometer2Outlined: <Thermometer2Outlined />,
  Thermometer3Outlined: <Thermometer3Outlined />,
  ThermometerColdOutlined: <ThermometerColdOutlined />,
  ThermometerWarmOutlined: <ThermometerWarmOutlined />,
  ThumbsDownOutlined: <ThumbsDownOutlined />,
  ThumbsUpOutlined: <ThumbsUpOutlined />,
  Ticket1Outlined: <Ticket1Outlined />,
  Ticket2Outlined: <Ticket2Outlined />,
  Toggle1LeftOutlined: <Toggle1LeftOutlined />,
  Toggle1RightOutlined: <Toggle1RightOutlined />,
  Toggle2LeftOutlined: <Toggle2LeftOutlined />,
  Toggle2RightOutlined: <Toggle2RightOutlined />,
  Toggle3LeftOutlined: <Toggle3LeftOutlined />,
  Toggle3RightOutlined: <Toggle3RightOutlined />,
  Tool1Outlined: <Tool1Outlined />,
  Tool2Outlined: <Tool2Outlined />,
  TrainOutlined: <TrainOutlined />,
  TramOutlined: <TramOutlined />,
  TransformOutlined: <TransformOutlined />,
  Translate1Outlined: <Translate1Outlined />,
  Translate2Outlined: <Translate2Outlined />,
  Trash1Outlined: <Trash1Outlined />,
  Trash2Outlined: <Trash2Outlined />,
  Trash3Outlined: <Trash3Outlined />,
  Trash4Outlined: <Trash4Outlined />,
  TrendDown1Outlined: <TrendDown1Outlined />,
  TrendDown2Outlined: <TrendDown2Outlined />,
  TrendUp1Outlined: <TrendUp1Outlined />,
  TrendUp2Outlined: <TrendUp2Outlined />,
  TriangleOutlined: <TriangleOutlined />,
  Trophy1Outlined: <Trophy1Outlined />,
  Trophy2Outlined: <Trophy2Outlined />,
  Truck1Outlined: <Truck1Outlined />,
  Truck2Outlined: <Truck2Outlined />,
  Tv1Outlined: <Tv1Outlined />,
  Tv2Outlined: <Tv2Outlined />,
  Tv3Outlined: <Tv3Outlined />,
  Twitter1Outlined: <Twitter1Outlined />,
  Type1Outlined: <Type1Outlined />,
  Type2Outlined: <Type2Outlined />,
  TypeSquareOutlined: <TypeSquareOutlined />,
  TypeStrikethrough1Outlined: <TypeStrikethrough1Outlined />,
  TypeStrikethrough2Outlined: <TypeStrikethrough2Outlined />,
  Umbrella1Outlined: <Umbrella1Outlined />,
  Umbrella2Outlined: <Umbrella2Outlined />,
  Umbrella3Outlined: <Umbrella3Outlined />,
  Underline1Outlined: <Underline1Outlined />,
  Underline2Outlined: <Underline2Outlined />,
  UnderlineSquareOutlined: <UnderlineSquareOutlined />,
  Upload1Outlined: <Upload1Outlined />,
  Upload2Outlined: <Upload2Outlined />,
  Upload3Outlined: <Upload3Outlined />,
  Upload4Outlined: <Upload4Outlined />,
  UploadCloud1Outlined: <UploadCloud1Outlined />,
  UploadCloud2Outlined: <UploadCloud2Outlined />,
  UsbFlashDriveOutlined: <UsbFlashDriveOutlined />,
  User1Outlined: <User1Outlined />,
  User2Outlined: <User2Outlined />,
  User3Outlined: <User3Outlined />,
  UserSleepOutlined: <UserSleepOutlined />,
  UserCheck1Outlined: <UserCheck1Outlined />,
  UserCheck2Outlined: <UserCheck2Outlined />,
  UserCircleOutlined: <UserCircleOutlined />,
  UserDown1Outlined: <UserDown1Outlined />,
  UserDown2Outlined: <UserDown2Outlined />,
  UserEditOutlined: <UserEditOutlined />,
  UserLeft1Outlined: <UserLeft1Outlined />,
  UserLeft2Outlined: <UserLeft2Outlined />,
  UserMinus1Outlined: <UserMinus1Outlined />,
  UserMinus2Outlined: <UserMinus2Outlined />,
  UserPlus1Outlined: <UserPlus1Outlined />,
  UserPlus2Outlined: <UserPlus2Outlined />,
  UserRight1Outlined: <UserRight1Outlined />,
  UserRight2Outlined: <UserRight2Outlined />,
  UserSquareOutlined: <UserSquareOutlined />,
  UserUp1Outlined: <UserUp1Outlined />,
  UserUp2Outlined: <UserUp2Outlined />,
  UserX1Outlined: <UserX1Outlined />,
  UserX2Outlined: <UserX2Outlined />,
  Users1Outlined: <Users1Outlined />,
  Users2Outlined: <Users2Outlined />,
  Users3Outlined: <Users3Outlined />,
  UsersCheckOutlined: <UsersCheckOutlined />,
  UsersDownOutlined: <UsersDownOutlined />,
  UsersEditOutlined: <UsersEditOutlined />,
  UsersLeftOutlined: <UsersLeftOutlined />,
  UsersMinusOutlined: <UsersMinusOutlined />,
  UsersPlusOutlined: <UsersPlusOutlined />,
  UsersRightOutlined: <UsersRightOutlined />,
  UsersUpOutlined: <UsersUpOutlined />,
  UsersXOutlined: <UsersXOutlined />,
  VariableOutlined: <VariableOutlined />,
  VideoRecorderOffOutlined: <VideoRecorderOffOutlined />,
  VideoRecorderOutlined: <VideoRecorderOutlined />,
  VirusOutlined: <VirusOutlined />,
  VoicemailOutlined: <VoicemailOutlined />,
  VolumeMaxOutlined: <VolumeMaxOutlined />,
  VolumeMinOutlined: <VolumeMinOutlined />,
  VolumeMinusOutlined: <VolumeMinusOutlined />,
  VolumePlusOutlined: <VolumePlusOutlined />,
  VolumeXOutlined: <VolumeXOutlined />,
  Wallet1Outlined: <Wallet1Outlined />,
  Wallet2Outlined: <Wallet2Outlined />,
  Wallet3Outlined: <Wallet3Outlined />,
  Wallet4Outlined: <Wallet4Outlined />,
  Wallet5Outlined: <Wallet5Outlined />,
  WatchCircleOutlined: <WatchCircleOutlined />,
  WatchSquareOutlined: <WatchSquareOutlined />,
  WavesOutlined: <WavesOutlined />,
  Webcam1Outlined: <Webcam1Outlined />,
  Webcam2Outlined: <Webcam2Outlined />,
  WifiOffOutlined: <WifiOffOutlined />,
  WifiOutlined: <WifiOutlined />,
  Wind1Outlined: <Wind1Outlined />,
  Wind2Outlined: <Wind2Outlined />,
  Wind3Outlined: <Wind3Outlined />,
  XCircleOutlined: <XCircleOutlined />,
  XCloseOutlined: <XCloseOutlined />,
  XSquareOutlined: <XSquareOutlined />,
  XOutlined: <XOutlined />,
  YoutubeOutlined: <YoutubeOutlined />,
  ZapCircleOutlined: <ZapCircleOutlined />,
  ZapFastOutlined: <ZapFastOutlined />,
  ZapOffOutlined: <ZapOffOutlined />,
  ZapSquareOutlined: <ZapSquareOutlined />,
  ZapOutlined: <ZapOutlined />,
  ZoomInOutlined: <ZoomInOutlined />,
  ZoomOutOutlined: <ZoomOutOutlined />,
  BottleOutlined: <BottleOutlined />,
  CakeOutlined: <CakeOutlined />,
  ClocheOutlined: <ClocheOutlined />,
  CoffeeCupOutlined: <CoffeeCupOutlined />,
  CookieOutlined: <CookieOutlined />,
  CupcakeOutlined: <CupcakeOutlined />,
  EggOutlined: <EggOutlined />,
  FemaleOutlined: <FemaleOutlined />,
  FishOutlined: <FishOutlined />,
  ForkKnifeCrossedOutlined: <ForkKnifeCrossedOutlined />,
  ForkKnifeOutlined: <ForkKnifeOutlined />,
  ForkSpoonCrossedOutlined: <ForkSpoonCrossedOutlined />,
  ForkSpoonOutlined: <ForkSpoonOutlined />,
  Glass1Outlined: <Glass1Outlined />,
  Glass2Outlined: <Glass2Outlined />,
  HamburgerOutlined: <HamburgerOutlined />,
  Invalid1Outlined: <Invalid1Outlined />,
  Invalid2Outlined: <Invalid2Outlined />,
  KnifeOutlined: <KnifeOutlined />,
  MaleOutlined: <MaleOutlined />,
  MartiniGlassCrossedOutlined: <MartiniGlassCrossedOutlined />,
  MartiniGlassOutlined: <MartiniGlassOutlined />,
  MugSaucerSteamOutlined: <MugSaucerSteamOutlined />,
  MugSaucerOutlined: <MugSaucerOutlined />,
  NonBinaryOutlined: <NonBinaryOutlined />,
  PizzaOutlined: <PizzaOutlined />,
  PopcornOutlined: <PopcornOutlined />,
  RestaurantMenuOutlined: <RestaurantMenuOutlined />,
  RoadSignOutlined: <RoadSignOutlined />,
  SignBothOutlined: <SignBothOutlined />,
  SignLeftOutlined: <SignLeftOutlined />,
  SignRightOutlined: <SignRightOutlined />,
  WineGlassOutlined: <WineGlassOutlined />
}

export default ICONS_NAMES
